#:schema ../schemas/dev/parser.schema.json

[adtl]
  name = ""
  description = ""

  [adtl.tables]
    study = { kind = "constant" }
    subject = { kind = "groupBy", groupBy = "subject_id", aggregation = "lastNotNull", schema = "../../schemas/dev/subject.schema.json" }
    visit = { kind = "groupBy", groupBy = "visit_id", aggregation = "lastNotNull", schema = "../../schemas/dev/visit.schema.json" }
    observation = { kind = "groupBy", groupBy = "", aggregation = "lastNotNull", schema = "../../schemas/dev/observation.schema.json" }

  [adtl.defs."Y/N/NK".values]
    1 = true
    2 = false

[study]
  id = ""
  date = ""
  country_iso3 = ""

  ## SUBJECT

[subject]
  study_id = ""
  subject_id = ""
  enrolment_date = ""
  age = ""
  sex_at_birth = ""
  ethnicity = ""
  country_iso3 = ""
  pathogen = ""


  ## VISITS

[visit]
  country_iso3 = "GBR"
  visit_id = ""
  start_date = ""
  subject_id = ""
  outcome = ""
  date_outcome = ""
