#:schema ../schemas/dev/parser.schema.json

[adtl]
  name = ""
  description = ""

  [adtl.tables]
    study = { kind = "constant" }
    subject = { kind = "groupBy", groupBy = "subject_id", aggregation = "lastNotNull", schema = "../../schemas/dev/subject.schema.json" }
    visit = { kind = "groupBy", groupBy = "visit_id", aggregation = "lastNotNull", schema = "../../schemas/dev/visit.schema.json" }
    observation = { kind = "groupBy", groupBy = "", aggregation = "lastNotNull", schema = "../../schemas/dev/observation.schema.json" }

  [adtl.defs."Y/N/NK".values]
    1 = true
    2 = false

  [adtl.defs.ethnicityMap.values]
    1 = "White"
    2 = "Arab"
    3 = "Black"
    4 = "East_Asian"
    5 = "South_Asian"
    6 = "West_Asian"
    7 = "Latin_American"

[adtl.defs.admissionDateHierarchy]
  combinedType = "firstNonNull"
  fields = [
    { field = "hostdat", description = "Admission date at this facility" },
    { field = "cestdat", description = "Onset date of first/earliest symptom" },
    { field = "dsstdat", description = "Date of enrolment" },
    { field = "daily_dsstdat", description = "Date of assessment" },
  ]

[adtl.defs.followupDateHierarchy]
  combinedType = "firstNonNull"
  fields = [
    { field = "flw_survey_date", description = "About you and your COVID-19 illness (if you're completing this survey on behalf of a child or adult that you care for, all the questions relate to their health and wellbeing)" },
    { field = "dsstdtc", description = "Outcome date", if = { dsterm = 4 } },
    { field = "dsstdtc_v2", description = "Outcome date", if = { dsterm_v2 = 4 } },
  ]

[adtl.defs.inabilityWalk.values]
  2 = "slight"
  3 = "moderate"
  4 = "severe"
  5 = "unable"

[adtl.defs.countryMap.values]
  1 = "AFG"
  2 = "ALB"
  3 = "DZA"
  4 = "AND"
  5 = "AGO"
  6 = "ATG"
  7 = "ARG"
  8 = "ARM"
  9 = "AUS"
  10 = "AUT"
  11 = "AZE"
  12 = "BHS"
  13 = "BHR"
  14 = "BGD"
  15 = "BRB"
  16 = "BLR"
  17 = "BEL"
  18 = "BLZ"
  19 = "BEN"
  20 = "BTN"
  21 = "BOL"
  22 = "BIH"
  23 = "BWA"
  24 = "BRA"
  25 = "BRN"
  26 = "BGR"
  27 = "BFA"
  28 = "BDI"
  29 = "KHM"
  30 = "CMR"
  31 = "CAN"
  32 = "CPV"
  33 = "CAF"
  34 = "TCD"
  35 = "CHL"
  36 = "CHN"
  37 = "COL"
  38 = "COM"
  39 = "COG"
  40 = "COD"
  41 = "CRI"
  42 = "HRV"
  43 = "CUB"
  44 = "CYP"
  45 = "CZE"
  46 = "DNK"
  47 = "DJI"
  48 = "DMA"
  49 = "DOM"
  50 = "TLS"
  51 = "ECU"
  52 = "EGY"
  53 = "SLV"
  54 = "GNQ"
  55 = "ERI"
  56 = "EST"
  57 = "ETH"
  58 = "FJI"
  59 = "FIN"
  60 = "FRA"
  61 = "GAB"
  62 = "GMB"
  63 = "GEO"
  64 = "DEU"
  65 = "GHA"
  66 = "GRC"
  67 = "GRD"
  68 = "GTM"
  69 = "GIN"
  70 = "GNB"
  71 = "GUY"
  72 = "HTI"
  73 = "HND"
  74 = "HUN"
  75 = "ISL"
  76 = "IND"
  77 = "IDN"
  78 = "IRN"
  79 = "IRQ"
  80 = "IRL"
  81 = "ISR"
  82 = "ITA"
  83 = "CIV"
  84 = "JAM"
  85 = "JPN"
  86 = "JOR"
  87 = "KAZ"
  88 = "KEN"
  89 = "KIR"
  90 = "PRK"
  91 = "KOR"
  92 = "XXK"
  93 = "KWT"
  94 = "KGZ"
  95 = "LAO"
  96 = "LVA"
  97 = "LBN"
  98 = "LSO"
  99 = "LBR"
  100 = "LBY"
  101 = "LIE"
  102 = "LTU"
  103 = "LUX"
  104 = "MKD"
  105 = "MDG"
  106 = "MWI"
  107 = "MYS"
  108 = "MDV"
  109 = "MLI"
  110 = "MLT"
  111 = "MHL"
  112 = "MRT"
  113 = "MUS"
  114 = "MEX"
  115 = "FSM"
  116 = "MDA"
  117 = "MCO"
  118 = "MNG"
  119 = "MNE"
  120 = "MAR"
  121 = "MOZ"
  122 = "MMR"
  123 = "NAM"
  124 = "NRU"
  125 = "NPL"
  126 = "NLD"
  127 = "NZL"
  128 = "NIC"
  129 = "NER"
  130 = "NGA"
  131 = "NOR"
  132 = "OMN"
  133 = "PAK"
  134 = "PLW"
  135 = "PAN"
  136 = "PNG"
  137 = "PRY"
  138 = "PER"
  139 = "PHL"
  140 = "POL"
  141 = "PRT"
  142 = "QAT"
  143 = "ROU"
  144 = "RUS"
  145 = "RWA"
  146 = "KNA"
  147 = "LCA"
  148 = "VCT"
  149 = "WSM"
  150 = "SMR"
  151 = "STP"
  152 = "SAU"
  153 = "SEN"
  154 = "SRB"
  155 = "SYC"
  156 = "SLE"
  157 = "SGP"
  158 = "SVK"
  159 = "SVN"
  160 = "SLB"
  161 = "SOM"
  162 = "ZAF"
  163 = "SSD"
  164 = "ESP"
  165 = "LKA"
  166 = "SDN"
  167 = "SUR"
  168 = "SWZ"
  169 = "SWE"
  170 = "CHE"
  171 = "SYR"
  172 = "TWN"
  173 = "TJK"
  174 = "TZA"
  175 = "THA"
  176 = "TGO"
  177 = "TON"
  178 = "TTO"
  179 = "TUN"
  180 = "TUR"
  181 = "TKM"
  182 = "TUV"
  183 = "UGA"
  184 = "UKR"
  185 = "ARE"
  186 = "GBR"
  187 = "USA"
  188 = "URY"
  189 = "UZB"
  190 = "VUT"
  191 = "VAT"
  192 = "VEN"
  193 = "VNM"
  194 = "YEM"
  195 = "ZMB"
  196 = "ZWE"

[study]
  id = ""
  date = ""
  country_iso3 = { field = "country", ref = "countryMap" }

  ## SUBJECT

[subject]
  study_id = ""
  country_iso3 = { field = "country", ref = "countryMap" }
  pathogen = ""

  [subject.subject_id]
    field = ""
    description = ""
    sensitive = true

  [subject.enrolment_date]
    field = ""
    description = ""

  [subject.age]
    field = ""
    description = ""

  [subject.sex_at_birth]
    field = ""
    description = ""
    values = { 1 = "male", 2 = "female", 3 = "nonbinary" }

  [subject.ethnicity]
    field = ""
    description = ""

  [subject.admission_date]
    field = ""
    description = ""

  [subject.works_microbiology_lab]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.works_healthcare]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.pregnancy]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.pregnancy_date_of_delivery]
    field = ""
    description = ""

  [subject.pregnancy_birth_weight_kg]
    field = ""
    description = ""

  [subject.pregnancy_outcome]
    field = ""
    description = ""

  [subject.pregnancy_gestational_outcome]
    field = ""
    description = ""
    values = { 1 = "Term birth", 2 = "Preterm birth" }

  [subject.pregnancy_whether_breastfed]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.pregnancy_post_partum]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.pregnancy_gestational_assessment_weeks]
    field = ""
    description = ""

  [subject.has_chronic_hematologic_disease]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_asplenia]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_tuberculosis]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_dementia]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_obesity]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_rheumatologic_disorder]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_hiv]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_hypertension]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_malignant_neoplasm]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_smoking]
    field = ""
    description = ""
    values = { 1 = "yes", 2 = "former", 3 = "never" }

  [subject.has_asthma]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_chronic_cardiac_disease]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_chronic_kidney_disease]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_diabetes]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.diabetes_type]
    field = ""
    description = ""
    values = { 1 = "type-1", 2 = "type-2", 3 = "gestational" }

  [subject.has_liver_disease]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_apnoea]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_hiv_viral_suppression]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_inflammatory_bowel_disease]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_rare_disease_inborn_metabolism_error]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_solid_organ_transplant]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_tuberculosis_past]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_hiv_art]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_immunosuppression_therapy_treatment]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.has_comorbidity_other]
    field = ""
    description = ""

  [subject.has_died]
    field = ""
    description = ""
    ref = "Y/N/NK"

  [subject.date_death]
    field = ""
    description = ""

  [subject.icu_admitted]
    field = ""
    description = ""
    ref = "Y/N/NK"

    ## VISITS

[visit]
  country_iso3 = { field = "country", ref = "countryMap" }

  [visit.visit_id]
    field = ""
    description = ""
    sensitive = true

  [visit.start_date]
    field = ""
    description = ""

  [visit.subject_id]
    field = ""
    description = ""
    sensitive = true

  [visit.outcome]
    field = ""
    description = ""

    [visit.outcome.values]
      1 = "discharged"
      2 = "hospitalised"
      3 = "transferred"
      4 = "death"
      5 = "recovered"

[visit.date_outcome]
  field = ""
  description = ""

[visit.dataset_id]
  field = ""
  description = ""

[visit.end_date]
  field = ""
  description = ""

[visit.pathogen_test_date]
  field = ""
  description = ""

[visit.phase]
  field = ""
  description = ""
  values = { 1 = "admission", 2 = "study", 3 = "followup" }

[visit.icu_admission]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.icu_admission_dates]
  field = ""
  description = ""

[visit.treatment_dialysis]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_inotropes_vasopressors]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_ecmo]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_corticosteroid]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_oxygen_therapy]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_prone_position]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_invasive_ventilation]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_antifungal_agent]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_antivirals]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_antibiotics]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_anticoagulation]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_experimental_agent]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_inhaled_nitric_oxide]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_noninvasive_ventilation]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_ace_inhibitors]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_arb]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_antimalarial]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_dexamethasone]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_high_flow_nasal_cannula]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_steroids]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_immunosuppressant]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_intravenous_fluids]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_nsaid]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_neuraminidase]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_oxygen_interface]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_cpr]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_offlabel]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_respiratory_support]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_tocilizumab]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_indication_anticoagulation]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_cardiovascular]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_colchicine]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_immunoglobulins]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_delirium]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_monoclonal_antibody]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_other]
  field = ""
  description = ""

[visit.treatment_oxygen_mechanical_support]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_pacing]
  field = ""
  description = ""
  ref = "Y/N/NK"

[visit.treatment_o2_flow_vol_max]
  field = ""
  description = ""

[[observation]]
  name = "avpu"
  date = "admissionDateHierarchy"
  phase = "admission"
  is_present = { field = "", values = {} }
  if = {}
  value = ""
  text = { field = "", values = {} }
  context = ""
