[adtl]
name = "isaric-ccpuk"
description = "ISARIC CCPUK study"

[adtl.tables.study]
kind = "constant"

[adtl.tables.subject]
kind = "groupBy"
groupBy = "subject_id"
aggregation = "lastNotNull"
schema = "../../schemas/dev/subject.schema.json"

[adtl.tables.visit]
kind = "groupBy"
groupBy = "visit_id"
aggregation = "lastNotNull"
schema = "../../schemas/dev/visit.schema.json"

[adtl.tables.observation]
kind = "groupBy"
groupBy = ""
aggregation = "lastNotNull"
schema = "../../schemas/dev/observation.schema.json"

[adtl.defs."Y/N/NK".values]
1 = true
2 = false
3 = false

[study]
id = "isaric-ccpuk"
date = "2021-01-01"
country_iso3 = "GBR"

[subject]
study_id = "isaric-ccpuk"
country_iso3 = "GBR"
pathogen = "COVID-19"

[subject.age_years]
field = "age_estimateyears"
description = ""
unit = "years"

[subject.age_years.source_unit]
field = "age_estimatedyearsu"

[subject.age_years.source_unit.values]
1 = "year"
2 = "month"

[subject.sex_at_birth]
field = "sex"
description = "Sex at birth"

[subject.sex_at_birth.values]
1 = "male"
2 = "female"
3 = "nonbinary"

[subject.works_microbiology_lab]
field = "labwork_erterm"
description = ""
ref = "Y/N/NK"

[visit]
country_iso3 = "GBR"
