#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "ccp-guinea"
  description = "ccp-guinea"

  [adtl.tables.subject]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/subject.schema.json"

  [adtl.tables.visit]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/visit.schema.json"

  [adtl.tables.observation]
    kind = "oneToMany"
    schema = "../../schemas/dev/observation.schema.json"
    common = { visit_id = { field = "subjid", sensitive = true } }

[adtl.defs]
  "Y/N/NK" = { values = { 1 = true, 2 = false } }
  "positive/negative" = { values = { 1 = "positive", 2 = "negative" } }

  [adtl.defs.countryMap.values]
    1 = "AFG"
    2 = "ALB"
    3 = "DZA"
    4 = "AND"
    5 = "AGO"
    6 = "ATG"
    7 = "ARG"
    8 = "ARM"
    9 = "AUS"
    10 = "AUT"
    11 = "AZE"
    12 = "BHS"
    13 = "BHR"
    14 = "BGD"
    15 = "BRB"
    16 = "BLR"
    17 = "BEL"
    18 = "BLZ"
    19 = "BEN"
    20 = "BTN"
    21 = "BOL"
    22 = "BIH"
    23 = "BWA"
    24 = "BRA"
    25 = "BRN"
    26 = "BGR"
    27 = "BFA"
    28 = "BDI"
    29 = "KHM"
    30 = "CMR"
    31 = "CAN"
    32 = "CPV"
    33 = "CAF"
    34 = "TCD"
    35 = "CHL"
    36 = "CHN"
    37 = "COL"
    38 = "COM"
    39 = "COG"
    40 = "COD"
    41 = "CRI"
    42 = "HRV"
    43 = "CUB"
    44 = "CYP"
    45 = "CZE"
    46 = "DNK"
    47 = "DJI"
    48 = "DMA"
    49 = "DOM"
    50 = "TLS"
    51 = "ECU"
    52 = "EGY"
    53 = "SLV"
    54 = "GNQ"
    55 = "ERI"
    56 = "EST"
    57 = "ETH"
    58 = "FJI"
    59 = "FIN"
    60 = "FRA"
    61 = "GAB"
    62 = "GMB"
    63 = "GEO"
    64 = "DEU"
    65 = "GHA"
    66 = "GRC"
    67 = "GRD"
    68 = "GTM"
    69 = "GIN"
    70 = "GNB"
    71 = "GUY"
    72 = "HTI"
    73 = "HND"
    74 = "HUN"
    75 = "ISL"
    76 = "IND"
    77 = "IDN"
    78 = "IRN"
    79 = "IRQ"
    80 = "IRL"
    81 = "ISR"
    82 = "ITA"
    83 = "CIV"
    84 = "JAM"
    85 = "JPN"
    86 = "JOR"
    87 = "KAZ"
    88 = "KEN"
    89 = "KIR"
    90 = "PRK"
    91 = "KOR"
    92 = "XXK"
    93 = "KWT"
    94 = "KGZ"
    95 = "LAO"
    96 = "LVA"
    97 = "LBN"
    98 = "LSO"
    99 = "LBR"
    100 = "LBY"
    101 = "LIE"
    102 = "LTU"
    103 = "LUX"
    104 = "MKD"
    105 = "MDG"
    106 = "MWI"
    107 = "MYS"
    108 = "MDV"
    109 = "MLI"
    110 = "MLT"
    111 = "MHL"
    112 = "MRT"
    113 = "MUS"
    114 = "MEX"
    115 = "FSM"
    116 = "MDA"
    117 = "MCO"
    118 = "MNG"
    119 = "MNE"
    120 = "MAR"
    121 = "MOZ"
    122 = "MMR"
    123 = "NAM"
    124 = "NRU"
    125 = "NPL"
    126 = "NLD"
    127 = "NZL"
    128 = "NIC"
    129 = "NER"
    130 = "NGA"
    131 = "NOR"
    132 = "OMN"
    133 = "PAK"
    134 = "PLW"
    135 = "PAN"
    136 = "PNG"
    137 = "PRY"
    138 = "PER"
    139 = "PHL"
    140 = "POL"
    141 = "PRT"
    142 = "QAT"
    143 = "ROU"
    144 = "RUS"
    145 = "RWA"
    146 = "KNA"
    147 = "LCA"
    148 = "VCT"
    149 = "WSM"
    150 = "SMR"
    151 = "STP"
    152 = "SAU"
    153 = "SEN"
    154 = "SRB"
    155 = "SYC"
    156 = "SLE"
    157 = "SGP"
    158 = "SVK"
    159 = "SVN"
    160 = "SLB"
    161 = "SOM"
    162 = "ZAF"
    163 = "SSD"
    164 = "ESP"
    165 = "LKA"
    166 = "SDN"
    167 = "SUR"
    168 = "SWZ"
    169 = "SWE"
    170 = "CHE"
    171 = "SYR"
    172 = "TWN"
    173 = "TJK"
    174 = "TZA"
    175 = "THA"
    176 = "TGO"
    177 = "TON"
    178 = "TTO"
    179 = "TUN"
    180 = "TUR"
    181 = "TKM"
    182 = "TUV"
    183 = "UGA"
    184 = "UKR"
    185 = "ARE"
    186 = "GBR"
    187 = "USA"
    188 = "URY"
    189 = "UZB"
    190 = "VUT"
    191 = "VAT"
    192 = "VEN"
    193 = "VNM"
    194 = "YEM"
    195 = "ZMB"
    196 = "ZWE"


[subject]
  pathogen = "COVID-19"

  [subject.subject_id]
    field = "record_id"
    sensitive = true

  [subject.admission_date]
    field = "rpt_date"

  [subject.country_iso3]
    field = "country"
    ref = "countryMap"

  [subject.sex_at_birth]
    field = "sex"
    values = { 0 = "male", 2 = "female" }
  [subject.age]
    field = "age"
    description = "Age"
    source_unit = { field = "age_unit", values = { 1 = "years", 2 = "months", 3 = "days" } }
    unit = "years"

  [subject.ethnicity]
    field = "other_ethnicity"
    description = "Other Ethnicity"

  [subject.has_asthma]
    field = "asthma"
    description = "Asthma (diagnosed by a physician)"
    ref = "Y/N/NK"

  [subject.has_chronic_cardiac_disease]
    field = "cardiac"
    description = "Chronic heart disease, including congenital heart disease (not hypertension)"
    ref = "Y/N/NK"

  [subject.has_chronic_hematologic_disease]
    field = "hem_dse"
    description = "Chronic blood disease"
    ref = "Y/N/NK"

  [subject.has_chronic_kidney_disease]
    combinedType = "any"

    [[subject.has_chronic_kidney_disease.fields]]
      field = "ckd"
      description = "Chronic kidney disease"
      ref = "Y/N/NK"

    [[subject.has_chronic_kidney_disease.fields]]
      field = "dialysis_disch"
      description = "Dialysis/kidney treatment"
      values = { 1 = true, 0 = false }

[subject.has_dementia]
  field = "demented"
  description = "Dementia"
  ref = "Y/N/NK"

[subject.has_diabetes]
  combinedType = "any"
  fields = [
    { field = "devil", description = "Diabetes with complication", ref = "Y/N/NK" },
    { field = "diab_comp", description = "Diabetes without complication", ref = "Y/N/NK" },
  ]

[subject.has_hiv]
  field = "helps"
  description = "HIV/AIDS"
  ref = "Y/N/NK"

[subject.has_hypertension]
  field = "hypertension"
  description = "Hypertension"
  ref = "Y/N/NK"

[subject.has_liver_disease]
  combinedType = "any"
  fields = [
    { field = "hep_dse_mild", description = "Mild liver disease", ref = "Y/N/NK" },
    { field = "hep_dse_mod_sev", description = "Moderate or severe liver disease", ref = "Y/N/NK" },
  ]

[subject.has_malignant_neoplasm]
  field = "neopla"
  description = "Malignant tumor"
  ref = "Y/N/NK"

[subject.has_malnutrition]
  field = "malnu"
  description = "Malnutrition"
  ref = "Y/N/NK"

[subject.has_obesity]
  field = "obesity"
  description = "Obesity (as defined by caregiver)"
  ref = "Y/N/NK"

[subject.has_solid_organ_transplant]
  field = "organ_rec"
  description = "Transplanted (organ or bone marrow)"
  ref = "Y/N/NK"

[subject.has_tuberculosis]
  field = "tuberculosis"
  description = "Tuberculosis"
  ref = "Y/N/NK"

[subject.icu_admitted]
  field = "overall_icu_hostdat"
  description = "Date of ICU admission:"

[subject.pregnancy]
  field = "upt_res"
  description = "Urine Dipstick Pregnancy Test Result"
  ref = "positive/negative"

[subject.pregnancy_birth_weight_kg]
  field = "birthweight"
  description = "Birth weight"

[subject.pregnancy_gestational_assessment_weeks]
  field = "gesture"
  description = "Gestational age"

[subject.works_healthcare]
  field = "work_loc"
  description = "Place of work (with location data)"

[subject.works_microbiology_lab]
  field = "work_loc"
  description = "Place of work (with location data)"

  # VISIT

[visit.subject_id]
  field = "rpt_date"
  sensitive = true

[visit.visit_id]
  field = "rpt_date"
  sensitive = true

[visit.country_iso3]
  field = "country"
  ref = "countryMap"

[visit.outcome]
  field = "outcome"

  [visit.outcome.values]
    1 = "discharged"
    2 = "recovered"
    3 = "transferred"
    4 = "death"
    5 = "discharged"  # released with home care
    6 = "discharged"  # released with palliative care

[visit.start_date]
  field = "rpt_date"

[visit.date_outcome]
  field = "outcome_date"

[visit.icu_admission]
  combinedType = "any"
  fields = [
    { field = "overall_icu_hostdat", description = "Date of ICU admission:" },
    { field = "overall_icu_hoendat", description = "Date of ICU discharge:" },
  ]

[visit.icu_admission_dates]
  combinedType = "set"
  fields = [
    { field = "overall_icu_hostdat", description = "Date of ICU admission" },
  ]

[visit.pathogen_test_date]
  field = "path_date"
  description = "Test date"

[visit.treatment_antibiotics]
  field = "daily_antibiot_cmyn"
  description = "Antibiotics"

[visit.treatment_antiviral_type]
  combinedType = "list"

  [[visit.treatment_antiviral_type.fields]]
    field = "daily_antiviral_cmoth"
    description = "Antivirals - If <i>Other antivirals</i>, specify"

  [[visit.treatment_antiviral_type.fields]]
    field = "other_ant_viral_prmd_other"
    description = "If Other type, specify"

[visit.treatment_antivirals]
  field = "daily_antiviral_cmoth"
  description = "Antivirals - If <i>Other antivirals</i>, specify"

[visit.treatment_dexamethasone]
  field = "dexamethasone"
  description = "Dexamethasone"
  values = { 1 = true, 0 = false }

[visit.treatment_dialysis]
  combinedType = "any"

  [[visit.treatment_dialysis.fields]]
    field = "dialysis_disch"
    description = "Dialysis/kidney treatment"
    values = { 1 = true, 0 = false }

  [[visit.treatment_dialysis.fields]]
    field = "dialy_hemo"
    description = "Dialysis/Hemofiltration?"
    ref = "Y/N/NK"

[visit.treatment_ecmo]
  field = "overall_extracorp_prtrt"
  description = "Extracorporeal (ECMO) support"
  ref = "Y/N/NK"

[visit.treatment_high_flow_nasal_cannula]
  field = "can_oxy_ther"
  description = "High flow oxygen therapy by nasal prongs?"
  ref = "Y/N/NK"

[visit.treatment_inotropes_vasopressors]
  field = "vaso_or_inot"
  description = "Any administration of vasopressor/inotrope?"
  ref = "Y/N/NK"

[visit.treatment_invasive_ventilation]
  field = "inv_vent"
  description = "Invasive ventilation?"
  ref = "Y/N/NK"

[visit.treatment_noninvasive_ventilation]
  field = "non_inv_vent"
  description = "Non-invasive ventilation (eg BiPAP, CPAP)?"
  ref = "Y/N/NK"

[visit.treatment_other]
  combinedType = "set"
  fields = [
    { field = "premeds_other_meds2", description = "Other treatment (3)" },
    { field = "premeds_other_meds3", description = "Other treatment (4)" },
    { field = "premeds_other_meds1", description = "Other treatment (2)" },
  ]

[visit.treatment_oxygen_therapy]
  combinedType = "any"

  [[visit.treatment_oxygen_therapy.fields]]
    field = "o2_therapy_disch"
    description = "Oxygen therapy"
    values = { 1 = true, 0 = false }

  [[visit.treatment_oxygen_therapy.fields]]
    field = "can_oxy_ther"
    description = "High flow oxygen therapy by nasal prongs?"
    ref = "Y/N/NK"

[visit.treatment_prone_position]
  field = "overall_prone_prtrt"
  description = "Prone position"
  ref = "Y/N/NK"

[visit.treatment_steroids]
  combinedType = "any"

  [[visit.treatment_steroids.fields]]
    field = "systemic_steroids"
    description = "System steroid"
    values = { 1 = true, 0 = false }

  [[visit.treatment_steroids.fields]]
    field = "other_systemic"
    description = "Other systemic steroid"
    values = { 1 = true, 0 = false }

  [[visit.treatment_steroids.fields]]
    field = "inhale_steroids"
    description = "Inhalational/Nebulized steroid"
    values = { 1 = true, 0 = false }

  [[visit.treatment_steroids.fields]]
    field = "topical"
    description = "Topical steroids(including eyes/ear drops)"
    values = { 1 = true, 0 = false }

[[observation]]
  name = "base_excess"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { base_excess = { "!=" = "" } }
  text = { field = "base_excess", description = "Basic excess" }

[[observation]]
  name = "bleeding_haemorrhage"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { bleed_loc_v2 = { "!=" = "" } }
  text = { field = "bleed_loc_v2", description = "In case of bleeding specify the site(s)" }

[[observation]]
  name = "bleeding_haemorrhage"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { bleed_loc = { "!=" = "" } }
  text = { field = "bleed_loc", description = "In case of bleeding specify the site(s)" }

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { diastol_iso = { "!=" = "" } }
  text = { field = "diastol_iso", description = "Diastolic blood pressure (BP diastolic)" }

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { diastol = { "!=" = "" } }
  text = { field = "diastol", description = "Diastolic BP" }

[[observation]]
  name = "from_same_blood_gas_record_as_pao2"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { pcc02_source = { "!=" = "" } }

  [observation.is_present]
    field = "pcc02_source"
    description = "From the same blood gas recording a PaO2"
    values = { 1 = true, 0 = false }

[[observation]]
  name = "glasgow_coma_score"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { gcs_15 = { "!=" = "" } }
  text = { field = "gcs_15", description = "Glasgow score" }

[[observation]]
  name = "glasgow_coma_score"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { gcs = { "!=" = "" } }
  text = { field = "gcs", description = "Value Glasgow Score (SG/15)" }

[[observation]]
  name = "heart_rate_bpm"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { pulse_iso = { "!=" = "" } }
  text = { field = "pulse_iso", description = "Heart Rate (HR)" }

[[observation]]
  name = "heart_rate_bpm"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { hr = { "!=" = "" } }
  text = { field = "hr", description = "Heart Rate Value (HR)" }

[[observation]]
  name = "other_symptom"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { other_0_v2 = { "!=" = "" } }
  text = { field = "other_0_v2", description = "Other symptom 1" }

[[observation]]
  name = "other_symptom"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { other_0 = { "!=" = "" } }
  text = { field = "other_0", description = "Other symptom 1" }

[[observation]]
  name = "other_symptom"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { other_2 = { "!=" = "" } }
  text = { field = "other_2", description = "Other symptom 3" }

[[observation]]
  name = "other_symptom"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { other_1_v2 = { "!=" = "" } }
  text = { field = "other_1_v2", description = "Other symptom 2" }

[[observation]]
  name = "other_symptom"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { other_2_v2 = { "!=" = "" } }
  text = { field = "other_2_v2", description = "Other symptom 3" }

[[observation]]
  name = "other_symptom"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { premeds_other_meds2 = { "!=" = "" } }
  text = { field = "premeds_other_meds2", description = "Other treatment (3)" }

[[observation]]
  name = "oxygen_saturation_percent"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { oxygen_saturation = { "!=" = "" } }
  text = { field = "oxygen_saturation", description = "Oxygen saturation" }

[[observation]]
  name = "oxygen_saturation_percent"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { oxy_vsorres = { "!=" = "" } }
  text = { field = "oxy_vsorres", description = "Oxygen saturation" }

[[observation]]
  name = "oxygen_saturation_percent"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { o2_sate = { "!=" = "" } }
  text = { field = "o2_sate", description = "Oxygen saturation" }

[[observation]]
  name = "pH"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { urine_ph = { "!=" = "" } }
  text = { field = "urine_ph", description = "Urine pH" }

[[observation]]
  name = "renal_replacement_therapy_dialysis"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { dialy_hemo = { "!=" = 3 } }
  is_present = { field = "dialy_hemo", description = "Dialysis/Hemofiltration?", ref = "Y/N/NK" }

[[observation]]
  name = "respiratory_rate"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { rr = { "!=" = "" } }
  text = { field = "rr", description = "Respiratory rate (RR)" }

[[observation]]
  name = "respiratory_rate"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { rr_iso = { "!=" = "" } }
  text = { field = "rr_iso", description = "Respiratory rate (RR)" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { systol_iso = { "!=" = "" } }
  text = { field = "systol_iso", description = "Systolic blood pressure (BP systolic)" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { systolic = { "!=" = "" } }
  text = { field = "systolic", description = "Systolic BP" }

[[observation]]
  name = "temperature_celsius"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }
  if = { temperature_iso = { "!=" = "" } }
  text = { field = "temperature_iso", description = "Temperature" }

[[observation]]
  name = "temperature_celsius"
  phase = "study"
  date = { ref = "dailyDateHierarchy" }
  if = { temperature = { "!=" = "" } }
  text = { field = "temperature", description = "Value Temperature" }
