#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "ccp-spain"
  description = "COVID-19 patient data, Hospital del Mar, Barcelona, Spain"

  [adtl.tables.subject]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/subject.schema.json"

  [adtl.tables.visit]
    kind = "groupBy"
    groupBy = "visit_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/visit.schema.json"

  [adtl.tables.observation]
    kind = "oneToMany"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/observation.schema.json"
    common = { visit_id = { field = "record_id", sensitive = true } }

  [adtl.defs."Y/N/NK".values]
    0 = false
    1 = true
    # 2 = "Unknown"

[adtl.defs."outcomeDate"]
  combinedType = "firstNonNull"
  description = "Outcome date"
  fields = [
    { field = "fch_alta", if = { "outcome" = 2 } },
    { field = "fch_exitus", if = { "outcome" = 3 } },
  ]

[subject]
  pathogen = "COVID-19"

  [subject.sex_at_birth]
    field = "sex"
    description = "Sex at Birth"
    values = { 0 = "female", 1 = "male" }

  [subject.subject_id]
    field = "record_id"
    sensitive = true
    description = "Participant Identification Number (PIN) specify CPMS Site code (hyphen) four to six digit number patient number e.g. Y0401-0001."

  [subject.earliest_admission_date]
    fields = [{ field = "fchadminsion" }]
    combinedType = "min"
    description = "Date of admission to first study visit"
    # there is no field that maps to enrolment_date

  [subject.ethnicity]
    description = "Ethnic groups"
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "raza", values = { 1 = "White", 2 = "Black", 3 = "Hispanic", 4 = "Asian", 5 = "Arab", 6 = "Other" } },
    ]

  [subject.works_lab]
    field = "infhospi"
    description = "laboratory staff"
    values = { 2 = true }

  [subject.works_healthcare]
    field = "infhospi"
    values = { 1 = true }
    description = "Employed as a healthcare worker?"

  [subject.age]
    field = "edad"
    unit = "years"
    description = "Calculated age in years"

  [subject.date_of_birth]
    field = "fecha_nac"

  [subject.dob_year]
    field = "fecha_nac"
    apply = { function = "splitDate", params = ["year", 2022] }

  [subject.dob_month]
    field = "fecha_nac"
    apply = { function = "splitDate", params = ["month", 2022] }

  [subject.dob_day]
    field = "fecha_nac"
    apply = { function = "splitDate", params = ["day", 2022] }

  [subject.pregnancy]
    field = "embarazo"
    ref = "Y/N/NK"
    description = "Pregnant ?"

  [subject.pregnancy_gestational_age_weeks]
    field = "semgest"
    description = "Gestational weeks assessment"

  [subject.has_chronic_hematologic_disease]
    field = "co_tumorhemato"
    ref = "Y/N/NK"
    description = "Chronic hematologic disease (malignancy)"

  [subject.has_dementia]
    field = "co_demencia"
    ref = "Y/N/NK"
    description = "Dementia"

  [subject.has_obesity]
    field = "co_obesid"
    ref = "Y/N/NK"
    description = "Obesity (as defined by clinical staff)"

  [subject.has_hiv]
    field = "vih"
    ref = "Y/N/NK"
    description = "AIDS/HIV"

  [subject.has_hypertension]
    field = "co_hta"
    ref = "Y/N/NK"
    description = "Hypertension (physician diagnosed)"

  [subject.has_smoking]
    field = "co_fumador"
    values = { 1 = "yes", 0 = "never", 2 = "former" }

  [subject.has_asthma]
    field = "co_asma"
    ref = "Y/N/NK"
    description = "Asthma (physician diagnosed)"

  [subject.has_chronic_cardiac_disease]
    field = "co_cardiop"
    ref = "Y/N/NK"
    description = "Chronic cardiac disease, including congenital heart disease (not hypertension)"

  [subject.has_chronic_kidney_disease]
    field = "co_erc"
    ref = "Y/N/NK"
    description = "Chronic kidney disease"

  [subject.has_malignant_neoplasm]
    field = "co_neosolido"
    ref = "Y/N/NK"
    description = "Malignant neoplasm"

  [subject.has_chronic_respiratory_disease]
    field = "co_enfpulm"
    ref = "Y/N/NK"
    description = "Chronic respiratory disease"

  [subject.has_diabetes]
    field = "co_dm"
    ref = "Y/N/NK"
    description = "Diabetes without complications"

  [subject.has_comorbidity_other]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "co_otros2", if = { co_otros = 1 }, description = "Any other comorbidity" },
    ]

  [subject.has_liver_disease]
    field = "co_cirrosis"
    ref = "Y/N/NK"
    description = "Has liver disease"

  [subject.has_malnutrition]
    field = "co_malnutricion"
    description = "Patient is malnourished"
    ref = "Y/N/NK"

  [subject.date_death]
    field = "fch_exitus"
    description = "Date of death"
    if = { outcome = 3 }

  [subject.has_died]
    field = "outcome"
    description = "Has the subject died since being enroled in the study?"
    values = { 1 = false, 2 = false, 3 = true }

  [subject.icu_admitted]
    field = "uci"
    description = "Admitted to ICU?"
    values = { 0 = false, 1 = true }

[visit]
  country_iso3 = "ESP"

  [visit.visit_id]
    field = "record_id"
    sensitive = true

  [visit.subject_id] # same as visit_id!
    field = "record_id"
    sensitive = true

  [visit.start_date]
    field = "fchadminsion"
    description = "Admission date at this facility"


  [visit.icu_admission]
    combinedType = "any"
    fields = [{ field = "uci", values = { 0 = false, 1 = true } }]

  [visit.icu_admission_dates]
    description = "ICU admission date"
    combinedType = "list"
    excludeWhen = "none"
    fields = [{ field = "fecha_uci" }]

  [visit.pathogen_test_date]
    field = "fch_covid19"

  [visit.treatment_antibiotics]
    description = "Antibiotic agent?"
    field = "atb"
    values = { 0 = false, 1 = true }

  [visit.treatment_antibiotics_type]
    combinedType = "set"
    excludeWhen = 'false-like'
    fields = [{ field = "azt", values = { 1 = "Azithromycin" } }]

  [visit.treatment_antifungal_agent]
    description = "Antifungal agent?"
    field = "antif"
    values = { 0 = false, 1 = true }

  [visit.treatment_antivirals]
    description = "Antiviral agent?"
    combinedType = "any"
    fields = [
      { field = "rbv", values = { 0 = false, 1 = true }, description = "Ribavirin Antiviral?" },
      { field = "remdi", values = { 0 = false, 1 = true }, description = "Remdesivir Antiviral?" },
      { field = "lopr", values = { 0 = false, 1 = true }, description = "Lopinavir/Ritonvir Antiviral?" },
      { field = "oselt", values = { 0 = false, 1 = true }, description = "Neuraminidase inhibitors" },
      { field = "drv_c", values = { 0 = false, 1 = true }, description = "Darunavir/Cobicistat" },
      { field = "drv_r", values = { 0 = false, 1 = true }, description = "Darunavir/Ritonavir" },
    ]

  [visit.treatment_antiviral_type]
    description = "Type of antiviral agent used"
    excludeWhen = "none"
    combinedType = "set"
    fields = [
      { field = "rbv", values = { 1 = "Ribavirin" } },
      { field = "remdi", values = { 1 = "Remdesivir" } },
      { field = "lopr", values = { 1 = "Lopinavir/Ritonavir" } },
      { field = "oselt", values = { 1 = "Neuraminidase inhibitor" } },
      { field = "drv_c", values = { 1 = "Darunavir/Cobicistat" } },
      { field = "drv_r", values = { 1 = "Lopinavir/Ritonavir" } },
    ]

  [visit.treatment_antimalarial]
    description = "Antimalarial"
    combinedType = "any"
    fields = [
      { field = "cloroq", values = { 0 = false, 1 = true }, description = "Hydroxychloroquine" },
      { field = "cloroquina", values = { 0 = false, 1 = true }, description = "Chloroquine" },
    ]

  [visit.treatment_antimalarial_type]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "cloroq", values = { 1 = "Hydroxychloroquine" } },
      { field = "cloroquina", values = { 1 = "Chloroquine" } },
    ]

  [visit.treatment_immunosuppressant]
    description = "Other immunosuppressant (non-steroidal)"
    field = "tozi"
    values = { 0 = false, 1 = true }

  [visit.treatment_corticosteroid]
    description = "Corticosteroid agent?"
    field = "cortis"
    values = { 0 = false, 1 = true }

  [visit.treatment_dialysis]
    description = "Renal replacement therapy (RRT) or dialysis"
    field = "t_hd"
    values = { 0 = false, 1 = true }

  [visit.treatment_ecmo]
    description = "Extracorporeal (ECMO) support"
    field = "t_ecmo"
    values = { 0 = false, 1 = true }

  [visit.treatment_oxygen_therapy]
    description = "Oxygen therapy"
    field = "t_o2"
    values = { 0 = false, 1 = true }

  [visit.treatment_noninvasive_ventilation]
    description = "Non-invasive ventilation"
    field = "t_vmni"
    values = { 0 = false, 1 = true }

  [visit.treatment_invasive_ventilation]
    description = "Invasive ventilation?"
    field = "t_iot"
    values = { 0 = false, 1 = true }

  [visit.treatment_cardiovascular_support]
    combinedType = "any"
    fields = [
      { field = "t_dva", description = "Inotropes / vasopressors", values = { 0 = false, 1 = true } },
      { field = "t_ecmo", description = "Extracorporeal (ECMO) support", values = { 0 = false, 1 = true } },
    ]

  [visit.treatment_inotropes_vasopressors]
    description = "Inotropes / vasopressors"
    field = "t_dva"
    values = { 0 = false, 1 = true }

  [visit.outcome]
    combinedType = "firstNonNull"

    [[visit.outcome.fields]]
      field = "outcome"

      [visit.outcome.fields.values]
        2 = "discharged"
        1 = "hospitalised"
        3 = "death"

[visit.treatment_other]
  combinedType = "set"
  excludeWhen = "none"
  fields = [
    { field = "otro_tto", description = "Any other treatments for Covid?" },
    { field = "t_otros1", description = "Any other treatments?" },
  ]

[visit.date_outcome]
  combinedType = "firstNonNull"
  description = "Outcome date"
  fields = [
    { field = "fch_alta", if = { "outcome" = 2 } },
    { field = "fch_exitus", if = { "outcome" = 3 } },
  ]

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date = { field = "fchadminsion" }
  phase = "admission"
  value = { field = "sv_tad" }

[[observation]]
  name = "abdominal_pain"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_dolorabdominal", ref = "Y/N/NK" }

[[observation]]
  name = "altered_consciousness_confusion"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_consciencia", ref = "Y/N/NK" }

[[observation]]
  name = "chest_pain"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_dt", ref = "Y/N/NK" }

[[observation]]
  name = "cough"
  date = { field = "fchadminsion" }
  phase = "admission"

  [observation.is_present]
    combinedType = "any"
    fields = [
      { field = "ss_tos", ref = "Y/N/NK" },
      { field = "ss_hemop", ref = "Y/N/NK" },
      { field = "ss_exp", ref = "Y/N/NK" },
    ]

[[observation]]
  name = "cough_dry"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_tos", ref = "Y/N/NK" }

[[observation]]
  name = "cough_with_haemoptysis"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_hemop", ref = "Y/N/NK" }

[[observation]]
  name = "cough_with_sputum_production"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_exp", ref = "Y/N/NK" }

[[observation]]
  name = "diarrhoea"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_diarrea", ref = "Y/N/NK" }

[[observation]]
  name = "headache"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_cefalea", ref = "Y/N/NK" }

[[observation]]
  name = "history_of_fever"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_fever", ref = "Y/N/NK" }

[[observation]]
  name = "joint_pain"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_mialartral", ref = "Y/N/NK" }

[[observation]]
  name = "loss_of_smell"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_anosmia", ref = "Y/N/NK" }

[[observation]]
  name = "loss_of_smell_or_taste"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_anosmia", ref = "Y/N/NK" }

[[observation]]
  name = "seizures"
  date = { ref = "outcomeDate" }
  start_date = { field = "fchadminsion" }
  duration_type = "event"
  phase = "study"
  is_present = { field = "c_crisis", ref = "Y/N/NK" }

[[observation]]
  name = "seizures"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_convulsion", ref = "Y/N/NK" }

[[observation]]
  name = "shortness_of_breath"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_disnea", ref = "Y/N/NK" }

[[observation]]
  name = "skin_rash"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_rash", ref = "Y/N/NK" }

[[observation]]
  name = "vomiting_nausea"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_nausea", ref = "Y/N/NK" }

[[observation]]
  name = "pneumonia"
  phase = "study"
  start_date = { field = "fchadminsion" }
  duration_type = "event"
  date = { ref = "outcomeDate" }
  is_present = { field = "c_nb", ref = "Y/N/NK" }
  context = ["bacterial"]

[[observation]]
  name = "heart_rate_bpm"
  date = { field = "fchadminsion" }
  phase = "admission"
  value = { field = "sv_fc" }

[[observation]]
  name = "oxygen_saturation_percent"
  date = { field = "fchadminsion" }
  phase = "admission"
  value = { field = "sv_sat" }

[[observation]]
  name = "pao2_mmHg"
  date = { field = "fecha_gas" }
  phase = "admission"
  value = { field = "pa02", source_unit = "mmHg" }

[[observation]]
  name = "pco2_mmHg"
  date = { field = "fecha_gas" }
  phase = "admission"
  value = { field = "pco2" }

[[observation]]
  name = "oxygen_o2hb"
  date = { field = "fch_hemat" }
  phase = "admission"
  value = { field = "hb", source_unit = "g/dL", unit = "g/dL" }

[[observation]]
  name = "respiratory_rate"
  date = { field = "fchadminsion" }
  phase = "admission"
  value = { field = "sv_fresp" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date = { field = "fchadminsion" }
  phase = "admission"
  value = { field = "sv_tas" }

[[observation]]
  name = "temperature_celsius"
  date = { field = "fchadminsion" }
  phase = "admission"
  value = { field = "sv_temp" }

[[observation]]
  name = "fatigue_malaise"
  date = { field = "fchadminsion" }
  phase = "admission"
  is_present = { field = "ss_malest", ref = "Y/N/NK" } # this field onlz captured malaise, not fatigue

  ### Obervation attributes not mapped here...
  # bleeding
  # has_immunosuppression
  # avpu
  # clinical_classification_critical_illness_scale
  # clinical_classification_pneumonia_needing_oxygen
  # clinical_frailty_score
  # anorexia
  # base_excess
  # conjunctivitis
  # cyanosis
  # ear_pain
  # fatigue_malaise
  # feeding_intolerence_peadiatrics
  # hepatomegaly
  # inability_to_walk
  # inability_to_walk_scale
  # irritability_peadiatrics
  # loss_of_taste
  # lung_sounds
  # lymphadenopathy
  # lower_chest_wall_indrawing
  # muscle_aches
  # total_fluid_output_m
  # heart_sounds
  # mid_upper_arm_circumference_cm
  # mean_arterial_blood_pressure_mmHg
  # severe_dehydration
  # skin_ulcers
  # richmond_agitation-sedation_scale
  # riker_sedation-agitation_scale
  # pH
  # transfer_from_other_facility
  # time_of_admission
  # sternal_capillary_refill_time_greater_2s
  # runny_nose
  # wheezing
  # oxygen_flow_volume_max
  # oxygen_o2hb
  # sore_throat
