#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "ccp-netherlands"
  description = "MST Enschede"

  [adtl.tables.subject]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/subject.schema.json"

  [adtl.tables.visit]
    kind = "groupBy"
    groupBy = "visit_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/visit.schema.json"

  [adtl.tables.observation]
    kind = "oneToMany"
    schema = "../../schemas/dev/observation.schema.json"
    common = { visit_id = { field = "record_id", sensitive = true } }

  [adtl.defs."Y/N".values] # THIS CAN CHANGE BETWEEN DATASETS
    1 = true
    2 = false
    3 = false

    # other adtl.defs here ..

    # SUBJECT
    # required fields - subject_id, country_iso3, admission_date, age, sex_at_birth, ethnicity, pathogen

[subject]
  pathogen = "COVID-19"

  [subject.subject_id]
    field = "record_id"
    sensitive = true

  [subject.enrolment_date]
    field = "Enrolment_date"

  [subject.earliest_admission_date]
    field = "admission_dt"

  [subject.age]
    field = "age"
    source_unit = { field = "age_unit", values = { 1 = "years", 2 = "months" } } # best guess at units
    unit = "years"

  [subject.sex]
    field = "gender"

    [subject.sex.values] # This is standard...
      1 = "male"
      2 = "female"

[subject.ethnicity]
  combinedType = "set"
  excludeWhen = "none"
  fields = [
    { field = "ethnic_group#Arab", values = { 1 = "Arab" } },
    { field = "ethnic_group#Black", values = { 1 = "Black" } },
    { field = "ethnic_group#East_Asian", values = { 1 = "East Asian" } },
    { field = "ethnic_group#South_Asian", values = { 1 = "South Asian" } },
    { field = "ethnic_group#West_Asian", values = { 1 = "West Asian" } },
    { field = "ethnic_group#Latin_America", values = { 1 = "Latin American" } },
    { field = "ethnic_group#White", values = { 1 = "White" } },
    { field = "ethnic_group#AboriginalFirst_Nations", values = { 1 = "Aboriginal/First Nations" } },
    { field = "ethnic_group#Unknown", values = { 1 = "Unknown" } },
  ]


[subject.works_microbiology_lab]
  field = "mocrobiology_worker"
  ref = "Y/N"

[subject.works_healthcare]
  field = "healthcare_worker"
  ref = "Y/N"

[subject.pregnancy]
  field = "Pregnancy"
  ref = "Y/N"

[subject.pregnancy_post_partum]
  field = "post_partum"
  ref = "Y/N"

[subject.pregnancy_gestational_age_weeks]
  field = "gestational_weeks"

[subject.has_chronic_hematologic_disease]
  field = "chd" # ?
  ref = "Y/N"

[subject.has_chronic_cardiac_disease]
  field = "ccd"
  ref = "Y/N"

[subject.has_chronic_kidney_disease]
  field = "hkd"
  ref = "Y/N"

[subject.has_chronic_respiratory_disease]
  field = "hpd" # pulmonary disease?
  ref = "Y/N"

[subject.has_dementia]
  field = "Dementia"
  ref = "Y/N"

[subject.has_obesity]
  field = "obesity"
  ref = "Y/N"

[subject.has_rheumatologic_disorder]
  field = "rheuma_disorder"
  ref = "Y/N"

[subject.has_hiv]
  field = "aids_hiv"
  ref = "Y/N"

[subject.has_hypertension]
  field = "baseline_hypertension"
  ref = "Y/N"

[subject.has_malignant_neoplasm]
  field = "mneoplasm"
  ref = "Y/N"

[subject.has_smoking]
  field = "Smoking"

  [subject.has_smoking.values] # these 3 are present, who knows if the mapping is correct
    1 = "yes"
    2 = "former"
    3 = "never"

[subject.has_asthma]
  field = "asthma"
  ref = "Y/N"

[subject.has_diabetes]
  combinedType = "any"
  fields = [
    { field = "diabetes_complications", ref = "Y/N" },
    { field = "diabetes_without_complications", ref = "Y/N" },
  ]

[subject.has_liver_disease]
  combinedType = "any"
  fields = [
    { field = "live_disease", ref = "Y/N" },
    { field = "mld", ref = "Y/N" },
  ]

[subject.has_malnutrition]
  field = "Malnutrition"
  ref = "Y/N"

  [subject.has_comorbidity_other]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      {field = "Specif_other_risk_factors"}
    ]

[subject.has_died]
  field = "Outcome"
  values = { 4 = true }

[subject.date_death]
  field = "Outcome_dt"
  if = { Outcome = 4 }

[subject.icu_admitted]
  field = "ICU_High_Dependency_admission"
  ref = "Y/N"

  # VISIT
  # required fields - "visit_id", "subject_id", "country_iso3", "start_date", "outcome", "date_outcome"

[visit]
  country_iso3 = "NLD"

  [visit.visit_id]
    field = "record_id"
    sensitive = true

  [visit.subject_id]
    field = "record_id"
    sensitive = true

  [visit.start_date]
    field = "admission_dt"

  [visit.pathogen_test_date]
    field = "collection_dt"
    if = { Pathogen_tested_Detected_result = { "=~" = "sars-cov-2" } }

  [visit.icu_admission]
    combinedType = "any"
    fields = [
      { field = "current_in_ICU_ITU_IMU_HDU", ref = "Y/N" },    # these are over different lines, so probably won't work
      { field = "ICU_High_Dependency_admission", ref = "Y/N" },
    ]

  [visit.icu_admission_dates]
    field = "Admission_dt_icu"

  [visit.transfer_from_other_facility]
    field = "facility_transfer"
    values = { 1 = true, 2 = true, 3 = false }

  [visit.treatment_dialysis]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#DialysisHemofiltration", values = { 1 = true, 0 = false } },
      { field = "RRT_dialysis", ref = "Y/N" },
    ]

  [visit.treatment_inotropes_vasopressors]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Any_vasopressorinotropic_support", values = { 1 = true, 0 = false } },
      { field = "Inotropes_vasopressors", ref = "Y/N" },
    ]

  [visit.treatment_ecmo]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Extra_corporeal_life_support_ECLS", values = { 1 = true, 0 = false } },
      { field = "Extracorporeal_support", ref = "Y/N" },
    ]

  [visit.treatment_corticosteroid]
    field = "Corticosteroid"
    ref = "Y/N"

  [visit.treatment_corticosteroid_type]
    field = "Corticosteroid_type_dose"
    apply.function = "wordSubstituteSet"
    apply.params = [
      [
        "Hydrocortison",
        "Hydrocortisone",
      ],
      [
        "prednisolon",
        "Prednisolone",
      ],
      [
        "methylpredniolon",
        "Methyprednisolone",
      ],
      [
        "prednison",
        "Prednisone",
      ],
      [
        "dexamethason",
        "Dexamethasone",
      ],
    ]

  [visit.treatment_oxygen_therapy]
    combinedType = "any"
    fields = [
      { field = "Oxygen_therapy", ref = "Y/N" },
      { field = "patient_interventions#Invasive_ventilation", values = { 1 = true, 0 = false } },
      { field = "Invasive_ventilation", ref = "Y/N" },
      { field = "patient_interventions#Noninvasive_ventilation_eg_BIPAP_CPAP", values = { 1 = true, 0 = false } },
      { field = "Non_invasive_ventilation", ref = "Y/N" },
      { field = "patient_interventions#Highflow_nasal_canula_oxygen_therapy", values = { 1 = true, 0 = false } },
      { field = "patient_interventions#Extra_corporeal_life_support_ECLS", values = { 1 = true, 0 = false } },
      { field = "Extracorporeal_support", ref = "Y/N" },
    ]

  [visit.treatment_prone_position]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Prone_positioning", values = { 1 = true, 0 = false } },
      { field = "Prone_Ventilation", ref = "Y/N" },
    ]

  [visit.treatment_invasive_ventilation]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Invasive_ventilation", values = { 1 = true, 0 = false } },
      { field = "Invasive_ventilation", ref = "Y/N" },
    ]

  [visit.treatment_antifungal_agent]
    field = "Antifungal_agent"
    ref = "Y/N"

  [visit.treatment_antivirals]
    field = "Antiviral_agent"
    ref = "Y/N"

  [visit.treatment_antiviral_type]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "specify_Antiviral_agent#Ribavirin", values = { 1 = "Ribavarin" } },
      { field = "specify_Antiviral_agent#LopinavirRitonavir", values = { 1 = "Lopinavir/Ritonavir" } },
      { field = "specify_Antiviral_agent#Interferon_alpha", values = { 1 = "Interferon_alpha" } },
      { field = "specify_Antiviral_agent#Interferon_beta", values = { 1 = "Interferon_beta" } },
      { field = "specify_Antiviral_agent#Neuraminidase_inhibitor", values = { 1 = "Neuraminidase inhibitor" } },
    ]

  [visit.treatment_antiviral_type_other]
    combinedType = "set"
    excludeWhen = "none"
    fields = [{ field = "Specify_other_Antiviral_agent" }]

  [visit.treatment_antibiotics]
    field = "Antibiotic"
    ref = "Y/N"

  [visit.treatment_inhaled_nitric_oxide]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Inhaled_Nitric_Oxide", values = { 1 = true, 0 = false } },
      { field = "Inhaled_Nitric_Oxide", ref = "Y/N" },
    ]

  [visit.treatment_noninvasive_ventilation]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Noninvasive_ventilation_eg_BIPAP_CPAP", values = { 1 = true, 0 = false } },
      { field = "Non_invasive_ventilation", ref = "Y/N" },
    ]

  [visit.treatment_high_flow_nasal_cannula]
    field = "patient_interventions#Highflow_nasal_canula_oxygen_therapy"
    values = { 1 = true, 0 = false }

  [visit.treatment_cardiovascular_support]
    combinedType = "any"
    fields = [
      { field = "patient_interventions#Extra_corporeal_life_support_ECLS", values = { 1 = true, 0 = false } },
      { field = "Extracorporeal_support", ref = "Y/N" },
      { field = "patient_interventions#Any_vasopressorinotropic_support", values = { 1 = true, 0 = false } },
      { field = "Inotropes_vasopressors", ref = "Y/N" },
    ]

  [visit.treatment_neuromuscular_blocking_agents]
    field = "patient_interventions#Neuromuscular_blocking_agents"
    values = { 1 = true, 0 = false }

  [visit.treatment_other]
    combinedType = "set"
    excludeWhen = "none"
    fields = [{ field = "Specify_other_intervention_procedure" }]

  [visit.outcome]
    field = "Outcome"

    [visit.outcome.values] # check correspondence of these values
      1 = "discharged"
      2 = "hospitalised"
      3 = "transferred"
      4 = "death"
      5 = "palliative discharge"

[visit.date_outcome]
  field = "Outcome_dt"

  # OBSERVATION
  # required fields - phase, date, name

[[observation]]
  name = "avpu"
  date = { field = "assessment_dt" }
  phase = "study"
  text = { field = "AVPU", values = { 1 = "Alert", 2 = "Verbal", 3 = "Pain", 4 = "Unresponsive" } }

[[observation]]
  name = "pneumonia"
  start_date = { field = "admission_dt" }
  date = { field = "Outcome_dt" }
  duration_type = "event"
  phase = "study"
  is_present = { field = "Viral_pneumonitis_1", ref = "Y/N" }
  context = ['viral']

[[observation]]
  name = "pneumonia"
  start_date = { field = "admission_dt" }
  date = { field = "Outcome_dt" }
  duration_type = "event"
  phase = "study"
  is_present = { field = "Bacterial_pneumonia_1", ref = "Y/N" }
  context = ['bacterial']

[[observation]]
  name = "pneumonia"
  start_date = { field = "admission_dt" }
  date = { field = "Outcome_dt" }
  duration_type = "event"
  phase = "study"
  is_present = { field = "COP_1", ref = "Y/N" }
  context = ['COP']

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date = { field = "admission_dt" }
  phase = "admission"
  value = { field = "dias_bp" }

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Diastolic_bp_value" }

[[observation]]
  name = "glasgow_coma_score"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Glasgow_Coma_Score" }

[[observation]]
  name = "abdominal_pain"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Abdominal_pain", ref = "Y/N" }

[[observation]]
  name = "altered_consciousness_confusion"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "confusion", ref = "Y/N" }

[[observation]]
  name = "base_excess"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Base_excess_value" }

[[observation]]
  name = "bleeding_haemorrhage"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Bleeding_Haemorrhage", ref = "Y/N" }

[[observation]]
  name = "chest_pain"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Chest_pain", ref = "Y/N" }

[[observation]]
  name = "conjunctivitis"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Conjunctavitis", ref = "Y/N" }

[[observation]]
  name = "cough"
  date = {field = "admission_dt"}
  phase = "admission"

  [observation.is_present]
    combinedType = "any"
    fields = [
      {field = "cough_sputum_haemoptysis", ref = "Y/N"},
      { field = "cough_sputum", ref = "Y/N" }
    ]

[[observation]]
  name = "cough_with_haemoptysis"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "cough_sputum_haemoptysis", ref = "Y/N" }

[[observation]]
  name = "cough_with_sputum_production"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "cough_sputum", ref = "Y/N" }

[[observation]]
  name = "diarrhoea"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Diarrhoea", ref = "Y/N" }

[[observation]]
  name = "ear_pain"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "ear_pain", ref = "Y/N" }

[[observation]]
  name = "fatigue_malaise"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Fatigue_Malaise", ref = "Y/N" }

[[observation]]
  name = "headache"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Headache", ref = "Y/N" }

[[observation]]
  name = "history_of_fever"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "fever", ref = "Y/N" }

[[observation]]
  name = "joint_pain"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Arthralgia", ref = "Y/N" }

[[observation]]
  name = "lower_chest_wall_indrawing"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Lower_chest_wall_indrawing", ref = "Y/N" }

[[observation]]
  name = "lymphadenopathy"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Lymphadenopathy", ref = "Y/N" }

[[observation]]
  name = "muscle_aches"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Myalgia", ref = "Y/N" }

[[observation]]
  name = "runny_nose"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Rhinorrhoea", ref = "Y/N" }

[[observation]]
  name = "seizures"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Seizures", ref = "Y/N" }

[[observation]]
  name = "seizures"
  start_date = { field = "admission_dt" }
  date = { field = "Outcome_dt" }
  duration_type = "event"
  phase = "study"
  is_present = { field = "Seizure_1", ref = "Y/N" }

[[observation]]
  name = "severe_dehydration"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "dehydration", ref = "Y/N" }

[[observation]]
  name = "shortness_of_breath"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Dyspnea", ref = "Y/N" }

[[observation]]
  name = "skin_rash"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Skin_rash", ref = "Y/N" }

[[observation]]
  name = "skin_ulcers"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Skin_ulcers", ref = "Y/N" }

[[observation]]
  name = "sore_throat"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Sore_throat", ref = "Y/N" }

[[observation]]
  name = "sternal_capillary_refill_time_greater_2s"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "sternal_capillary_refill_time", ref = "Y/N" }

[[observation]]
  name = "vomiting_nausea"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Vomiting_Nausea", ref = "Y/N" }

[[observation]]
  name = "wheezing"
  date = { field = "admission_dt" }
  phase = "admission"
  is_present = { field = "Wheezing", ref = "Y/N" }

[[observation]]
  name = "heart_rate_bpm"
  date = { field = "admission_dt" }
  phase = "admission"
  value = { field = "HtR" }

[[observation]]
  name = "mean_arterial_blood_pressure_mmHg"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Mean_Arterial_bp_value" }

[[observation]]
  name = "oxygen_o2hb"
  date = { field = "daily_crf_date" }
  phase = "study"
  value = { field = "Haemoglobin_value", unit = "g/dL", source_unit = { field = "Haemoglobin_unit", values = { 2 = "g/dL", 1 = "g/L", 3 = "mg/dL" } } }

[[observation]]
  name = "oxygen_saturation_percent"
  date = { field = "admission_dt" }
  phase = "admission"
  value = { field = "oxygen_saturation" }

  [observation.context]
    combinedType = "set"
    fields = [
      { field = "oxygen_saturation_on", values = { 1 = "room air", 2 = "on oxygen" } },
    ]

[[observation]]
  name = "pao2_mmHg"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Specify_PaO2_at_FIO2" } # unit?
  if.all = [
    { report_name_custom = { "=~" = "Daily case record form" } },
    { Specify_PaO2_at_FIO2 = { "!=" = "" } },
  ]

[[observation]]
  name = "pco2_mmHg"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Specify_PCO2" }
  if.all = [
    { report_name_custom = { "=~" = "Daily case record form" } },
    { Specify_PCO2 = { "!=" = "" } },
  ]

[[observation]]
  name = "respiratory_rate"
  date = { field = "admission_dt" }
  phase = "admission"
  value = { field = "rtr" }

[[observation]]
  name = "richmond_agitation-sedation_scale"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "RASS_value" }

[[observation]]
  name = "riker_sedation-agitation_scale"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "SAS_value" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date = { field = "admission_dt" }
  phase = "admission"
  value = { field = "sys_bp" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date = { field = "assessment_dt" }
  phase = "study"
  value = { field = "Systolic_bp_value" }

[[observation]]
  name = "temperature_celsius"
  date = { field = "admission_dt" }
  phase = "admission"
  value = { field = "Temperature", source_unit = { field = "Temperature_units", values = { 1 = "celsius", 2 = "farenheit" } }, unit = "celsius" }
