#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "ccp-uganda"
  description = "uganda - CPPInUseV20_Data"


  [adtl.tables.subject]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/subject.schema.json"
    optional-fields = ["ethnicity"]

  [adtl.tables.visit]
    kind = "groupBy"
    groupBy = "visit_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/visit.schema.json"

  [adtl.tables.observation]
    kind = "oneToMany"
    schema = "../../schemas/dev/observation.schema.json"
    common = { visit_id = { field = "record_id", sensitive = true } }

  [adtl.defs."Y/N".values]
    1 = true
    0 = false

[adtl.defs.admissionDateHierarchy]
  combinedType = "firstNonNull"
  fields = [
    { field = "add_date", description = "Admission date at this facility" },
    { field = "hospitalization_date", description = "Date of hospitalization" },
    { field = "onset_date", description = "Date of onset of symptoms (within 10days)" },
    { field = "signs_symps_date" },
  ]


  # SUBJECT
  # required fields - subject_id, country_iso3, admission_date, age, sex_at_birth, ethnicity, pathogen

[subject]
  study_id = "CVAFWWW"
  country_iso3 = "UGA"
  pathogen = "COVID-19"

  [subject.subject_id]
    field = "record_id"
    sensitive = true

  [subject.admission_date]
    ref = "admissionDateHierarchy"
    description = "Admission date at this facility"

  [subject.age]
    field = "age"
    source_unit = { field = "age_unit", values = { 1 = "years", 2 = "months", 3 = "days" } }
    unit = "years"

  [subject.sex_at_birth]
    field = "sex"
    description = "Gender"
    values = { 0 = "female", 1 = "male" }

  [subject.works_microbiology_lab]
    field = "occupation"
    values = { 1 = false, 2 = false, 3 = false, 4 = false, 5 = false, 6 = true, 7 = false, 8 = false, 9 = false, 10 = false, 11 = false, 12 = false }

  [subject.works_healthcare]
    field = "occupation"
    values = { 1 = false, 2 = false, 3 = false, 4 = false, 5 = true, 6 = false, 7 = false, 8 = false, 9 = false, 10 = false, 11 = false, 12 = false }

  [subject.pregnancy]
    combinedType = "any"
    fields = [
      { field = "pregnant", values = { 1 = true, 0 = false } },
      { field = "preg", values = { 1 = true } },
    ]

  [subject.pregnancy_date_of_delivery]
    field = "del_date"
    description = "Delivery date"

  [subject.pregnancy_birth_weight_kg]
    field = "birthweigh"
    description = "What was the birth weight"

  [subject.pregnancy_outcome]
    field = "del_outcome"
    description = "Outcome of Pregnancy"
    values = { 0 = "Still birth", 1 = "Live birth" }

  [subject.pregnancy_gestational_outcome]
    field = "gest_out"
    description = "What was the gestational outcome?"
    values = { 1 = "preterm_birth", 2 = "term_birth" }

  [subject.pregnancy_whether_breastfed]
    combinedType = "any"
    fields = [
      { field = "breastfed", description = "Was the child breastfed?", ref = "Y/N" },
      { field = "curr_breatfeed", ref = "Y/N" },
    ]

  [subject.pregnancy_post_partum]
    field = "preg"
    description = "Is the client pregnant or in postpartum period"
    values = { 1 = false, 2 = true, 3 = false }

  [subject.pregnancy_gestational_assessment_weeks]
    field = "gest"
    description = "Gestational age"

  [subject.has_chronic_hematologic_disease]
    field = "hem_dse"
    ref = "Y/N"

  [subject.has_hiv]
    combinedType = "any"
    fields = [
      { field = "hiv_aids", description = "Known history of HIV/AIDS", ref = "Y/N" },
      { field = "rct_hiv", description = "Results of rapid testing for HIV:", ref = "Y/N" },
    ]

  [subject.has_hypertension]
    field = "hypertens"
    ref = "Y/N"

  [subject.has_malignant_neoplasm]
    field = "neopla"
    ref = "Y/N"

  [subject.has_smoking]
    combinedType = "firstNonNull"
    fields = [
      { field = "smok", values = { 0 = "never", 1 = "yes", 2 = "former" } },
      { field = "smoke", values = { 0 = "never", 1 = "yes", 2 = "former" } },
    ]

  [subject.has_asthma]
    field = "asthma"
    ref = "Y/N"

  [subject.has_chronic_kidney_disease]
    field = "kidney_dse"
    ref = "Y/N"

  [subject.has_diabetes]
    field = "diab"
    ref = "Y/N"

  [subject.has_liver_disease]
    field = "liver_dse"
    ref = "Y/N"

  [subject.has_hiv_art]
    field = "art"
    ref = "Y/N"

  [subject.has_immunosuppression_therapy_treatment]
    field = "other_imm_supps_premed"
    apply = { function = "isNotNull" }

  [subject.has_died]
    field = "outcome"
    values = { 1 = false, 2 = true, 3 = false, 4 = false }

  [subject.date_death]
    field = "outcome_date"
    if = { "outcome" = 2 }

  [subject.icu_admitted]
    combinedType = "any"
    fields = [
      { field = "overall_icu_hoterm", ref = "Y/N" },
      { field = "on_admn", values = { 1 = true, 0 = false }, description = "Current admission to ICU/ITU/IMC/HDU?" },
      { field = "overall_icu_hostdat", apply = { function = "isNotNull" } },
      { field = "icu_date", apply = { function = "isNotNull" } },
    ]

    # VISIT
    # required fields - "visit_id", "subject_id", "country_iso3", "start_date", "outcome", "date_outcome"

[visit]
  country_iso3 = "UGA"

  [visit.visit_id]
    field = "record_id"
    sensitive = true

  [visit.subject_id]
    field = "record_id"
    sensitive = true

  [visit.start_date]
    ref = "admissionDateHierarchy"

  [visit.pathogen_test_date]
    combinedType = "firstNonNull"
    fields = [
      { field = "date_rdt" },
      { field = "date_rct" },
      { field = "path_date" },
    ]

  [visit.icu_admission]
    combinedType = "any"
    fields = [
      { field = "overall_icu_hoterm", ref = "Y/N" },
      { field = "on_admn", values = { 1 = true, 0 = false }, description = "Current admission to ICU/ITU/IMC/HDU?" },
    ]

  [visit.icu_admission_dates]
    description = "Date of ICU admission:"
    combinedType = "set"
    excludeWhen = "none"
    fields = [{ field = "overall_icu_hostdat" }]

  [visit.treatment_dialysis]
    combinedType = "any"
    fields = [
      { field = "overall_rrt_hem", description = "Dialysis/Hemofiltration?", ref = "Y/N" },
      { field = "dialys", description = "Dialysis/Hemofiltration?", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_inotropes_vasopressors]
    combinedType = "any"
    fields = [
      { field = "overall_inotrop_cmtrt", description = "Any vasopressor/inotropic support/?", values = { 1 = true, 0 = false } },
      { field = "vaso_or_inot", description = "Any vasopressor/inotropic support/?", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_ecmo]
    field = "overall_extracorp_prtrt"
    values = { 1 = true, 0 = false, 3 = false }

  [visit.treatment_corticosteroid]
    field = "meds_given"
    values = { 1 = false, 2 = false, 3 = false, 4 = false, 5 = false, 6 = false, 7 = false, 8 = true, 9 = false }

  [visit.treatment_oxygen_therapy]
    combinedType = "any"
    fields = [
      { field = "overall_oxygen_cmoccur", values = { 1 = true, 0 = false, 3 = false } },
      { field = "can_oxy_ther", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_prone_position]
    combinedType = "any"
    fields = [
      { field = "overall_prone_prtrt", values = { 1 = true, 0 = false, 3 = false } },
      { field = "prone", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_invasive_ventilation]
    combinedType = "any"
    fields = [
      { field = "overall_invasive_proccur", values = { 1 = true, 0 = false, 3 = false } },
      { field = "inv_vent", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_antivirals]
    combinedType = "any"
    fields = [
      { field = "meds_given", values = { 1 = false, 2 = false, 3 = false, 4 = false, 5 = true, 6 = false, 7 = false, 8 = false, 9 = false } },
      { field = "sup_meds_antivirals", apply = { function = "isNotNull" } },
    ]

  [visit.treatment_antibiotics]
    combinedType = "any"
    fields = [
      { field = "meds_given", values = { 1 = false, 2 = false, 3 = false, 4 = false, 5 = false, 6 = true, 7 = false, 8 = false, 9 = false } },
      { field = "daily_antibiotic", ref = "Y/N" },
      { field = "antibio_meds_oth", apply = { function = "isNotNull" } },
      { field = "sup_antibiotic_agent", apply = { function = "isNotNull" } },
    ]

  [visit.treatment_antibiotics_type]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "antibio_meds_oth" },
      { field = "sup_antibiotic_agent" },
    ]

  [visit.treatment_anticoagulation]
    field = "meds_given"
    values = { 1 = false, 2 = false, 3 = false, 4 = true, 5 = false, 6 = false, 7 = false, 8 = false, 9 = false }

  [visit.treatment_inhaled_nitric_oxide]
    combinedType = "any"
    fields = [
      { field = "overall_nitrcoxid", values = { 1 = true, 0 = false, 3 = false } },
      { field = "nitric_oxide", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_noninvasive_ventilation]
    combinedType = "any"
    fields = [
      { field = "overall_noninvasive_proccur", values = { 1 = true, 0 = false, 3 = false } },
      { field = "non_inv_vent", values = { 1 = true, 0 = false } },
    ]

  [visit.treatment_antimalarial]
    field = "daily_antimal"
    ref = "Y/N"

  [visit.treatment_high_flow_nasal_cannula]
    field = "can_oxy_ther"
    values = { 1 = true, 0 = false }

  [visit.treatment_intravenous_fluids]
    field = "daily_iv_fluids"
    ref = "Y/N"

  [visit.treatment_neuromuscular_blocking_agents]
    field = "neuro_block"
    values = { 1 = true, 0 = false }

  [visit.treatment_other]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "oth_interv_sp", description = "Specify Other intervention or procedure?" },
    ]

  [visit.outcome]
    field = "outcome"
    values = { 1 = "discharged", 2 = "death", 4 = "transferred" }

  [visit.date_outcome]
    field = "outcome_date"


    # OBSERVATION
    # required fields - phase, date, name

    # NOTE: Phase is unclear in some cases, data not provided for one of the main symptom forms.

[[observation]]
  name = "avpu"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  text = { field = "avpu", values = { 1 = "ALERT", 2 = "Only responsive to VOICE", 3 = "Only responsive to PAIN", 4 = "UNRESPONSIVE" } }

[[observation]]
  name = "avpu"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  text = { field = "avpu_study", values = { 1 = "ALERT", 2 = "Only responsive to VOICE", 3 = "Only responsive to PAIN", 4 = "UNRESPONSIVE" } }

  # [[observation]]
  #   name = "clinical_classification_pneumonia_needing_oxygen"
  #   date = { ref = "admissionDateHierarchy" }
  #   phase = "admission"
  #   is_present = { field = "clipneu", ref = "Y/N" } # This field just indicates pneumonia, not necc. oxygen

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "diastol_iso" }

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "diastol" }

[[observation]]
  name = "pco2"
  date = { field = "icu_date" }
  phase = "study"
  value = { field = "pcc02" }
  [observation.context]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "pcc02_source", values = { 1 = "From same blood gas record as PaO2" } },
      { field = "pc02_type", values = { 1 = "kPa", 2 = "mmHg" } },
    ]

[[observation]]
  name = "glasgow_coma_score"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "gcs" }

[[observation]] # This might actually be a pre-admission symptom
  name = "confusion"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "confused", ref = "Y/N" }

[[observation]]
  name = "base_excess"
  date = { field = "icu_date" }
  phase = "study"
  value = { field = "base_excess" }

[[observation]]
  name = "bleeding_haemorrhage"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "bleed", ref = "Y/N" }

[[observation]]
  name = "chest_pain"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "chest", ref = "Y/N" }

[[observation]]
  name = "conjunctivitis"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "conjunct", ref = "Y/N" }

[[observation]]
  name = "cough"
  phase = "admission"
  date = { ref = "admissionDateHierarchy" }

  [observation.is_present]
    combinedType = "firstNonNull"
    fields = [
      { field = "cof", ref = "Y/N" },
      { field = "sick_symp___2", values = { 1 = true, 0 = false } },
    ]

[[observation]]
  name = "diarrhoea"
  date = { field = "onset_date" }
  start_date = { field = "onset_date", apply = { function = "startDate", params = [
    14,
  ] } }
  duration_type = "event"
  phase = "admission"
  is_present = { field = "sick_symp___3", values = { 1 = true, 0 = false } }

[[observation]]
  name = "diarrhoea"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "diarr", ref = "Y/N" }

[[observation]]
  name = "ear_pain"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "ear_pain", ref = "Y/N" }

[[observation]]
  name = "fatigue_malaise"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "fatig", ref = "Y/N" }

[[observation]]
  name = "headache"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "head", ref = "Y/N" }

[[observation]]
  name = "history_of_fever"
  start_date = { field = "onset_date", apply = { function = "startDate", params = [
    14,
  ] } }
  date = { field = "onset_date" }
  duration_type = "event"
  phase = "admission"
  is_present = { field = "sick_symp___1", values = { 1 = true } }

[[observation]]
  name = "history_of_fever"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "fever_hist", ref = "Y/N" }

[[observation]]
  name = "inability_to_walk"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "assist", values = { 1 = true, 0 = false } }

[[observation]]
  name = "inability_to_walk"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "assist_study", values = { 1 = true, 0 = false } }

  # there are more 'walking' fields ..

[[observation]]
  name = "joint_pain"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "joint", ref = "Y/N" }

[[observation]]
  name = "joint_pain"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "jt_ache", ref = "Y/N" }

[[observation]]
  name = "loss_of_smell"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "smell", ref = "Y/N" }

[[observation]]
  name = "loss_of_taste"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "taste", ref = "Y/N" }

[[observation]]
  name = "lower_chest_wall_indrawing"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "indraw", ref = "Y/N" }

[[observation]]
  name = "muscle_aches"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "muscle", ref = "Y/N" }

[[observation]]
  name = "runny_nose"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "runny_nose", ref = "Y/N" }

[[observation]]
  name = "shortness_of_breath"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "breath", ref = "Y/N" }

[[observation]]
  name = "skin_rash"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "rash_skin", ref = "Y/N" }

[[observation]]
  name = "skin_ulcers"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "ulcer_skin", ref = "Y/N" }

[[observation]]
  name = "sore_throat"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "throat", ref = "Y/N" }

[[observation]]
  name = "sternal_capillary_refill_time_greater_2s"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "caps" }

[[observation]]
  name = "time_of_admission"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  text = { field = "add_time" }

[[observation]]
  name = "vomiting_nausea"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "vomi", ref = "Y/N" }

[[observation]]
  name = "wheezing"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "wheez", ref = "Y/N" }

[[observation]]
  name = "heart_rate_bpm"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "pulse_iso", ref = "Y/N" }

[[observation]]
  name = "heart_rate_bpm"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "hr_study", ref = "Y/N" }

[[observation]]
  name = "other_symptom"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  is_present = { field = "covid_symp", ref = "Y/N" }

[[observation]]
  name = "oxygen_saturation_percent"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "o2_satu" }

[[observation]]
  name = "pao2"
  phase = "study"
  date = { field = "icu_date" }
  value = { field = "pa02", description = "PaO2 at time of FiO2 above" }
  [observation.context]
    combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "pa02_samp_type", values = { 1 = "Arterial", 2 = "Venous", 3 = "Capillary" } },
      { field = "pa02_type", values = { 1 = "kPa", 2 = "mmHg" } },
    ]

[[observation]]
  name = "pH"
  date = { field = "icu_date" }
  phase = "study"
  value = { field = "ph" }

[[observation]]
  name = "respiratory_rate"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "rr_iso" }

[[observation]]
  name = "respiratory_rate"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "rr_study" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "systol_iso" }

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "systol" }

[[observation]]
  name = "temperature_celsius"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "temperature_iso" }

[[observation]]
  name = "temperature_celsius"
  date = { ref = "admissionDateHierarchy" }
  phase = "admission"
  value = { field = "temp_study" }
