#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "isaric-ecmo"
  description = "ISARIC ECMO study"

  [adtl.defs."Y/N/NK".values]
    1 = true
    2 = false

  [adtl.defs.ethnicityMap.values]
    1 = "White"
    2 = "Arab"
    3 = "Black"
    4 = "East_Asian"
    5 = "South_Asian"
    6 = "West_Asian"
    7 = "Latin_American"

[adtl.tables]
  study = { kind = "constant" }
  subject = { kind = "groupBy", groupBy = "subject_id", aggregation = "lastNotNull", schema = "../../schemas/dev/subject.schema.json" }
  # visit = { kind = "groupBy", groupBy = "visit_id", aggregation = "lastNotNull", schema = "../../schemas/dev/visit.schema.json" }

[study]
  id = "isaric-ecmo"
  country_iso3 = "GBR"

[subject]
  study_id = "ecmo"
  country_iso3 = "GBR"
  pathogen = "COVID-19"

  [subject.sex_at_birth]
    field = "sex"
    description = "Sex at Birth"
    values = { 1 = "male", 2 = "female", 3 = "non_binary" }

  [subject.subject_id]
    field = "\ufeffsubjid"
    sensitive = true
    description = "Participant Identification Number (PIN) specify CPMS Site code (hyphen) four to six digit number patient number e.g. Y0401-0001."

  [subject.enrolment_date]
    field = "dsstdat"
    description = "Date of Enrolment"

  [subject.admission_date]
    field = "hostdat"
    description = "Admission date at this facility"

  [subject.ethnicity] # TODO: need to add ethnic other field
    description = "Ethnic groups"
    combinedType = "list"
    excludeWhen = "none"
    fields = [
      { field = "ethnic___1", values = { 1 = "Arab" } },
      { field = "ethnic___2", values = { 1 = "Black" } },
      { field = "ethnic___3", values = { 1 = "East_Asian" } },
      { field = "ethnic___4", values = { 1 = "South_Asian" } },
      { field = "ethnic___5", values = { 1 = "West_Asian" } },
      { field = "ethnic___6", values = { 1 = "Latin_American" } },
      { field = "ethnic___7", values = { 1 = "White" } },
      { field = "ethnic___8", values = { 1 = "Aboriginal_First_Nations" } },
    ]

  [subject.works_microbiology_lab]
    field = "labwork_erterm"
    ref = "Y/N/NK"
    description = "Employed in a microbiology laboratory?"

  [subject.works_healthcare]
    field = "healthwork_erterm"
    ref = "Y/N/NK"
    description = "Employed as a healthcare worker?"

  [subject.age]
    combinedType = "firstNonNull"
    [[subject.age.fields]]
      field = "age_estimate10"
      unit = "years"
      description = "Calculated age in years"

    [[subject.age.fields]]
      field = "age_estimateyears"
      unit = "years"
      description = "Age/Estimated age"

      [subject.age.fields.source_unit]
        field = "age_estimateyearsu"
        values = { 1 = "months", 2 = "years", 3 = "days" }

[subject.pregnancy]
  field = "pregyn_rptestcd"
  ref = "Y/N/NK"
  description = "Pregnant?"

[subject.pregnancy_date_of_delivery]
  field = "dlvrdtc_rptestcd"
  description = "Delivery date"

[subject.pregnancy_birth_weight_kg]
  field = "apvs_weight"
  unit = "kg"
  description = "Birth weight"
  source_unit = { field = "apvs_weightu", values = { 1 = "kg", 2 = "lbs" } }

[subject.pregnancy_outcome]
  field = "pregout_rptestcd"
  description = "Pregnancy Outcome"
  values = { 1 = "Live birth", 2 = "Still birth" }

[subject.pregnancy_gestational_outcome]
  field = "apsc_gestout"
  description = "Gestational outcome"
  values = { 1 = "Term birth", 2 = "Preterm birth" }

[subject.pregnancy_whether_breastfed] # SK to check here!!
  combinedType = "any"
  description = "Breastfed"
  fields = [
    { field = "apsc_brfedind", ref = "Y/N/NK" },
    { field = "apsc_brfed", values = { 1 = true, 2 = true, 0 = false } },
  ]

[subject.pregnancy_post_partum]
  description = "Post Partum (within six weeks of delivery)"
  field = "postpart_rptestcd"
  values = { 1 = true, 0 = false }

[subject.pregnancy_gestational_assessment_weeks]
  field = "egestage_rptestcd"
  description = "Gestational weeks assessment"

[subject.has_chronic_hematologic_disease]
  field = "chronhaemo_mhyn"
  ref = "Y/N/NK"
  description = "Chronic hematologic disease"

[subject.has_asplenia]
  field = "asplenia_mhyn"
  ref = "Y/N/NK"
  description = "Asplenia"

[subject.has_tuberculosis]
  field = "tb_mhyn"
  ref = "Y/N/NK"
  description = "Tuberculosis"

[subject.has_dementia]
  field = "dementia_mhyn"
  ref = "Y/N/NK"
  description = "Dementia"

[subject.has_obesity]
  field = "obesity_mhyn"
  ref = "Y/N/NK"
  description = "Obesity (as defined by clinical staff)"

[subject.has_rheumatologic_disorder]
  field = "rheumatology_mhyr"
  ref = "Y/N/NK"
  description = "Rheumatologic disorder"

[subject.has_hiv]
  combinedType = "any"
  description = "AIDS/HIV"
  fields = [
    { field = "aidshiv_mhyn", ref = "Y/N/NK" },
    { field = "aidshiv_mhyn_2", values = { 1 = true, 2 = false, 4 = true } },
  ]

[subject.has_hypertension]
  field = "hypertension_mhyn"
  ref = "Y/N/NK"
  description = "Hypertension (physician diagnosed)"

[subject.has_malignant_neoplasm]
  field = "malignantneo_mhyn"
  ref = "Y/N/NK"
  description = "Malignant neoplasm"

[subject.has_smoking]
  field = "smoking_mhyn"
  values = { 1 = "yes", 2 = "never", 3 = "former" }

[subject.has_asthma]
  field = "asthma_mhyn"
  description = "Asthma (physician diagnosed)"
  values = { 1 = true, 0 = false }

[subject.has_chronic_cardiac_disease] # SK to check here!
  description = "Chronic cardiac disease, including congenital heart disease (not hypertension)"
  combinedType = "firstNonNull"
  fields = [
    { field = "chroniccard_mhyn", ref = "Y/N/NK", description = "Chronic cardiac disease" },
    # { field = "c_chd", values = { 1 = true, 0 = false }, description = "Congenital heart disease" },
    { field = "cardiomyopathy_ceterm", ref = "Y/N/NK", description = "Cardiomyopathy" },
    # { field = "c_pcmyo", values = { 1 = true, 0 = false }, description = "Pre-existing Cardiomyopathy" },
    # { field = "c_diagtak", values = { 1 = true, 0 = false }, description = "DIAGNOSIS OF TAKOTSUBO CARDIOMYOPATHY" },
  ]

[subject.has_chronic_kidney_disease]
  field = "renal_mhyn"
  ref = "Y/N/NK"
  description = "Chronic kidney disease"

[subject.has_diabetes] # NEED TO CHECK THIS!
  combinedType = "firstNonNull"
  fields = [
    # { field = "diabetes_spain", description = "Did the patient have diabetes?" },                 # this field has no values??!!!
    { field = "diabetiscomp_mhyn", ref = "Y/N/NK", description = "Diabetes with complications" },
    { field = "diabetes_mhyn", ref = "Y/N/NK", description = "Diabetes without complications" },
    { field = "diabetes_mhyn_2", values = { 1 = true, 2 = false, 4 = true, 5 = true } },          # based on diabetes type
  ]

[subject.diabetes_type]
  field = "diabetes_mhyn_2"
  description = "Diabetes and Type"
  values = { 1 = "type-1", 4 = "type-2", 5 = "gestational" }

[subject.has_liver_disease]
  combinedType = "any"
  fields = [
    { field = "modliver_mhyn", description = "Moderate liver disease", values = { 1 = true, 0 = false } },
    { field = "mildliv_mhyn", description = "Mild liver disease", values = { 1 = true, 0 = false } },
  ]

[subject.has_hiv_art]
  field = "aidshiv_mhyn_2"
  description = "patient is on ART (antiretroviral therapy)"
  values = { 1 = true, 2 = false, 4 = false }

[subject.has_immunosuppression_therapy_treatment]
  field = "pre_nonoralsteroid_cmoccur"
  ref = "Y/N/NK"
  description = "Other immunosuppressant agents (not oral steroids)"

  # [subject.has_solid_organ_transplant]  # None of the fields are available
  #   description = "Solid organ transplant recipients:"
  #   combinedType = "firstNonNull"
  #   fields = [
  #     { field = "f_lungt_yn", values = { 1 = true, 0 = false }, description = "Did this patient receive a lung transplant due to COVID-19 associated pulmonary complications?" },
  #     { field = "c_ptransplant", values = { 1 = true, 0 = false }, description = "Previous Cardiac transplant" },
  #   ]

[subject.date_death]
  combinedType = "firstNonNull"
  fields = [
    # { field = "f_datedeath", description = "Date of death", if = { dsterm = 4 } },
    { field = "dsstdtc", description = "Outcome date", if = { dsstdtcyn = 1 } },
  ]

[subject.icu_admitted]
  field = "icu_hoterm"
  description = "Admitted to ICU?"
  apply = { function = "isNotNull" } # WHAT DOES THIS DO?
