#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "isaric-rapid"
  description = "ISARIC RAPID study"

  [adtl.defs."Y/N/NK".values]
    1 = true
    2 = false

  [adtl.defs.ethnicityMap.values]
    1 = "White"
    2 = "Arab"
    3 = "Black"
    4 = "East_Asian"
    5 = "South_Asian"
    6 = "West_Asian"
    7 = "Latin_American"

[adtl.tables]
  study = { kind = "constant" }
  subject = { kind = "groupBy", groupBy = "subject_id", aggregation = "lastNotNull", schema = "../../schemas/dev/subject.schema.json" }
  visit = { kind = "groupBy", groupBy = "visit_id", aggregation = "lastNotNull", schema = "../../schemas/dev/visit.schema.json" }

[study]
  id = "isaric-rapid"
  country_iso3 = "GBR"

  ## SUBJECT

[subject]
  study_id = "isaric-rapid"
  country_iso3 = "GBR"
  pathogen = "COVID-19"

  [subject.sex_at_birth]
    field = "sex"
    description = "Sex at Birth"
    values = { 1 = "male", 2 = "female", 3 = "non_binary" }

  [subject.subject_id]
    field = "﻿subjid"
    sensitive = true
    description = "Participant Identification Number (PIN)"

  [subject.enrolment_date]
    field = "dsstdat"
    description = "Date of Enrolment"

  [subject.admission_date]
    field = "hostdat"
    description = "Admission date at this facility"

  [subject.ethnicity]
    description = "Ethnicity"
    combinedType = "list"
    excludeWhen = "none"
    fields = [
      { field = "flw_ethnicity", ref = "ethnicityMap" },
      { field = "flw2_ethnicity", ref = "ethnicityMap" },
      { field = "flw_ethnicity_oth", description = "Other ethnicity" },
      { field = "flw2_ethnicity_oth", description = "Other ethnicity" },
    ]

  [subject.works_microbiology_lab]
    field = "labwork_erterm"
    ref = "Y/N/NK"
    description = "Employed in a microbiology laboratory?"

  [subject.works_healthcare]
    field = "healthwork_erterm"
    ref = "Y/N/NK"
    description = "Employed as a healthcare worker?"

  [subject.age]
    description = "Age/Estimated age"
    combinedType = "firstNonNull"

    [[subject.age.fields]]
      field = "brthdtc"
      apply = { function = "yearsElapsed", params = ["dsstdat"] }

    [[subject.age.fields]]
      field = "age"
      unit = "years"
      source_unit = { field = "ageu", values = { 1 = "months", 2 = "years" } }

[subject.pregnancy]
  field = "pregyn_rptestcd"
  description = "Pregnant ?"
  values = { 0 = false, 1 = true }

[subject.pregnancy_date_of_delivery]
  field = "apdm_brthdat"
  description = "Delivery date"

[subject.pregnancy_birth_weight_kg]
  field = "apvs_weight_vsorres"
  source_unit = "grams"
  unit = "kg"
  description = "Birth weight"

[subject.pregnancy_outcome]
  field = "still_ceoccur"
  values = { 1 = "Still birth", 2 = "Live birth" }

[subject.pregnancy_gestational_assessment_weeks]
  field = "apsc_egestage_scorres"
  description = "Gestational weeks assessment"

[subject.has_hiv]
  field = "hiv_mborres"
  description = "AIDS/HIV"
  values = { 1 = true, 0 = false }

[subject.has_hypertension]
  field = "hypertension_mhyn"
  ref = "Y/N/NK"
  description = "Hypertension (physician diagnosed)"

[subject.has_malignant_neoplasm]
  field = "malignantneo_mhyn"
  ref = "Y/N/NK"
  description = "Malignant neoplasm"

[subject.has_smoking]
  field = "smoking_mhyn"
  values = { 1 = "yes", 2 = "never" } # TODO: How to get has_smoking=former?
  description = "Current smoking"

[subject.has_asthma]
  field = "asthma_mhyn"
  ref = "Y/N/NK"
  description = "Asthma (physician diagnosed)"

[subject.has_chronic_cardiac_disease]
  field = "chroniccard_mhyn"
  ref = "Y/N/NK"
  description = "Chronic cardiac disease, including congenital heart disease (not hypertension)"

[subject.has_chronic_kidney_disease]
  field = "renal_mhyn"
  ref = "Y/N/NK"
  description = "Chronic kidney disease"

[subject.has_asplenia]
  field = "asplenia_mhyn"
  ref = "Y/N/NK"
  description = "Asplenia"

[subject.has_tuberculosis]
  field = "tb_mhyn"
  ref = "Y/N/NK"
  description = "Tuberculosis"

[subject.has_died]
  field = "dsterm"
  description = "Death occurred"
  values = { 1 = false, 2 = false, 3 = false, 4 = true, 5 = false }

[subject.has_liver_disease]
  field = "liver_mhyn"
  ref = "Y/N/NK"
  description = "Liver disease"

[subject.date_death]
  field = "flw_date_death"
  description = "Date of death"

  ## VISIT

[visit]
  country_iso3 = "GBR"

  [visit.visit_id] # This is the same as the subject_id!
    field = "﻿subjid"
    sensitive = true

  [visit.start_date]
    combinedType = "firstNonNull"
    fields = [
      { field = "hostdat", description = "Admission date at this facility" },
      { field = "cestdat", description = "Onset date of first/earliest symptom" },
      { field = "flw_date_symptoms", description = "Roughly what day did you first experience symptoms of COVID-19?" },
      { field = "dsstdat", description = "Date of enrolment" },
      { field = "flw_survey_date", description = "About you and your COVID-19 illness (if you're completing this survey on behalf of a child or adult that you care for, all the questions relate to their health and wellbeing)" },
    ]

  [visit.subject_id]
    field = "﻿subjid"
    sensitive = true

  [visit.icu_admission]
    description = "ICU or High Dependency admission"
    combinedType = "firstNonNull"

    [[visit.icu_admission.fields]]
      field = "overall_icu_hoterm"
      ref = "Y/N/NK"
      description = "ICU or High Dependency admission?"

    [[visit.icu_admission.fields]]
      field = "daily_icu_hoterm"
      ref = "Y/N/NK"
      description = "ICU or High Dependency admission?"

    [[visit.icu_admission.fields]]
      field = "icu_hoterm"
      ref = "Y/N/NK"
      description = "ICU or High Dependency admission on the first day of admission?"

    [[visit.icu_admission.fields]]
      field = "ccm_a_icu_hoyn"
      description = "Current admission to ICU or other High Dependency Unit (HDU)?"
      values = { 0 = false, 1 = true, 2 = true, 3 = false }

[visit.treatment_ace_inhibitors]
  description = "Ace Inhibitors"
  combinedType = "firstNonNull"

  [[visit.treatment_ace_inhibitors.fields]]
    field = "daily_ace_cmoccur"
    ref = "Y/N/NK"
    description = "Angiotension converting enzyme inhibitors (ACE inhibitors)?"

  [[visit.treatment_ace_inhibitors.fields]]
    field = "ace_cmoccur"
    ref = "Y/N/NK"
    description = "Angiotensin converting enzyme inhibitors (ACE) on the first day of admission?"

[visit.treatment_antibiotics]
  description = "Antibiotics"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_antibiotic_cmyn", ref = "Y/N/NK", description = "Antibiotic?" },
    { field = "daily_antibiotic_cmyn", ref = "Y/N/NK", description = "Antibiotic?" },
    { field = "antibiotic_cmyn", ref = "Y/N/NK", description = "Antibiotic on the first day of admission?" },
  ]

[visit.treatment_anticoagulation]
  description = "Heparin for systemic anticoagulation?"
  field = "ccm_b_heparint_cmyn"
  ref = "Y/N/NK"

[visit.treatment_antifungal_agent]
  description = "Antifungal"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_antifung_cmyn", ref = "Y/N/NK", description = "Antifungal agent?" },
    { field = "daily_antifung_cmyn", ref = "Y/N/NK", description = "Antifungal agent?" },
    { field = "antifung_cmyn", ref = "Y/N/NK", description = "Antifungal agent on the first day of admission?" },
  ]

[visit.treatment_antimalarial]
  description = "Antimalarial"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_antimal_cmyn", ref = "Y/N/NK", description = "Antimalarial agent?" },
    { field = "daily_antimal_cmyn", ref = "Y/N/NK", description = "Antimalarial agent?" },
    { field = "antimal_cmyn", ref = "Y/N/NK", description = "Antimalarial agent on the first day of admission?" },
  ]

[visit.treatment_antivirals]
  description = "Antiviral"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_antiviral_cmyn", ref = "Y/N/NK", description = "Antiviral agent?" },
    { field = "daily_antiviral_cmyn", ref = "Y/N/NK", description = "Antiviral agent?" },
    { field = "antiviral_cmyn", ref = "Y/N/NK", description = "Antiviral agent on the first day of admission?" },
  ]

[visit.treatment_neuraminidase]
  description = "Antiviral type"
  combinedType = "firstNonNull"

  [[visit.treatment_neuraminidase.fields]]
    field = "overall_antiviral_cmtrt___5"
    description = "Neuraminidase used?"
    values = { 1 = true }
    if = { overall_antiviral_cmyn = 1 }

  [[visit.treatment_neuraminidase.fields]]
    field = "daily_antiviral_cmtrt___5"
    description = "Neuraminidase used?"
    values = { 1 = true }
    if = { daily_antiviral_cmyn = 1 }

  [[visit.treatment_neuraminidase.fields]]
    field = "antiviral_cmtrt___5"
    description = "Neuraminidase used?"
    values = { 1 = true }
    if = { antiviral_cmyn = 1 }

[visit.treatment_arb]
  description = "Angiotensin II receptor blockers (ARB)"
  combinedType = "firstNonNull"

  [[visit.treatment_arb.fields]]
    field = "daily_arb_cmoccur"
    ref = "Y/N/NK"
    description = "Angiotensin II receptor blockers (ARBs)?"

  [[visit.treatment_arb.fields]]
    field = "arb_cmoccur"
    ref = "Y/N/NK"
    description = "Angiotensin II receptor blockers (ARBs) on the first day of admission?"

[visit.treatment_cardiovascular]
  field = "ccm_b_horeas___4"
  Description = "Cardiovascular complications?"
  values = { 0 = false, 1 = true }
  if = { ccm_b_icu_yn = 1 }

[visit.treatment_corticosteroid]
  description = "Corticosteroid"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_corticost_cmyn", ref = "Y/N/NK", description = "Corticosteroid?" },
    { field = "daily_corticost_cmyn", ref = "Y/N/NK", description = "Corticosteroid?" },
    { field = "corticost_cmyn", ref = "Y/N/NK", description = "Corticosteroid on the first day of admission?" },
  ]

[visit.treatment_dexamethasone]
  description = "Dexamethasone used?"
  combinedType = "firstNonNull"

  [[visit.treatment_dexamethasone.fields]]
    field = "overall_corticost_cmtrt___1"
    description = "Dexamethasone used?"
    values = { 0 = false, 1 = true }
    if = { overall_corticost_cmyn = 1 }

  [[visit.treatment_dexamethasone.fields]]
    field = "daily_corticost_cmtrt___1"
    description = "Dexamethasone used?"
    values = { 0 = false, 1 = true }
    if = { daily_corticost_cmyn = 1 }

  [[visit.treatment_dexamethasone.fields]]
    field = "corticost_cmtrt___1"
    description = "Dexamethasone used?"
    values = { 0 = false, 1 = true }
    if = { corticost_cmyn = 1 }

[visit.treatment_dialysis]
  description = "Dialysis"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_rrt_prtrt", ref = "Y/N/NK", description = "Renal replacement therapy (RRT) or dialysis?" },
    { field = "daily_rrt_prtrt", ref = "Y/N/NK", description = "Renal replacement therapy (RRT) or dialysis?" },
    { field = "ccm_a_renal_prtrt", ref = "Y/N/NK", description = "Dialysis/Hemofiltration?" },
    { field = "ccm_b_renal_prtrt", ref = "Y/N/NK", description = "Dialysis/Hemofiltration?" },
  ]

[visit.treatment_ecmo]
  description = "ECMO"
  combinedType = "firstNonNull"

  [[visit.treatment_ecmo.fields]]
    field = "overall_extracorp_prtrt"
    ref = "Y/N/NK"
    description = "Extracorporeal (ECMO) support?"

  [[visit.treatment_ecmo.fields]]
    field = "daily_extracorp_prtrt"
    ref = "Y/N/NK"
    description = "Extracorporeal (ECMO) support?"

  [[visit.treatment_ecmo.fields]]
    field = "extracorp_prtrt"
    ref = "Y/N/NK"
    description = "Extracorporeal (ECMO) support on the first day of admission?"

[visit.treatment_experimental_agent]
  description = "Experimental treatments"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_exper_cmyn", ref = "Y/N/NK", description = "Experimental agent?" },
    { field = "daily_exper_cmyn", ref = "Y/N/NK", description = "Experimental agent?" },
    { field = "exper_cmyn", ref = "Y/N/NK", description = "Experimental agent on the first day of admission?" },
  ]

[visit.treatment_tocilizumab]
  description = "Experimental agents"
  combinedType = "firstNonNull"

  [[visit.treatment_tocilizumab.fields]]
    field = "overall_exper_cmtype___4"
    description = "Tocilizumab?"
    values = { 0 = false, 1 = true }
    if = { overall_exper_cmyn = 1 }

  [[visit.treatment_tocilizumab.fields]]
    field = "daily_exper_cmtype___4"
    description = "Tocilizumab?"
    values = { 0 = false, 1 = true }
    if = { daily_exper_cmyn = 1 }

  [[visit.treatment_tocilizumab.fields]]
    field = "exper_cmtype___4"
    description = "Tocilizumab?"
    values = { 0 = false, 1 = true }
    if = { exper_cmyn = 1 }

[visit.treatment_inotropes_vasopressors]
  description = "Inotropes/vasopressors"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_inotrop_cmtrt", ref = "Y/N/NK", description = "Inotropes/vasopressors?" },
    { field = "daily_inotrop_cmtrt", ref = "Y/N/NK", description = "Inotropes/vasopressors?" },
    { field = "inotrop_cmtrt", ref = "Y/N/NK", description = "Inotropes/vasopressors on the first day of admission?" },
    { field = "ccm_a_inotrop_cmtrt", ref = "Y/N/NK", description = "Any vasopressor/inotropic support?" },
  ]

[visit.treatment_intravenous_fluids]
  description = "IV fluids"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_iv_fluids_cmyn", ref = "Y/N/NK", description = "Intraveonous fluids?" },
    { field = "daily_iv_fluids_cmyn", ref = "Y/N/NK", description = "Intraveonous fluids?" },
    { field = "iv_fluids_cmyn", ref = "Y/N/NK", description = "Intraveonous fluids on the first day of admission?" },
  ]

[visit.treatment_invasive_ventilation]
  description = "Invasive ventilation"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_invasive_proccur", ref = "Y/N/NK", description = "Invasive ventilation?" },
    { field = "daily_invasive_proccur", ref = "Y/N/NK", description = "Invasive ventilation?" },
    { field = "invasive_proccur", ref = "Y/N/NK", description = "Invasive ventilation on first day of admission?" },
    { field = "ccm_b_invasive_prtrt", ref = "Y/N/NK", description = "Invasive ventilation?" },
  ]

[visit.treatment_noninvasive_ventilation]
  description = "Non-invasive ventilation"
  combinedType = "firstNonNull"

  [[visit.treatment_noninvasive_ventilation.fields]]
    field = "overall_noninvasive_proccur"
    ref = "Y/N/NK"
    description = "Non-invasive ventilation?"

  [[visit.treatment_noninvasive_ventilation.fields]]
    field = "daily_noninvasive_proccur"
    ref = "Y/N/NK"
    description = "Non-invasive ventilation?"

  [[visit.treatment_noninvasive_ventilation.fields]]
    field = "noninvasive_proccur"
    ref = "Y/N/NK"
    description = "Non-invasive ventilation on first day of admission?"

  [[visit.treatment_noninvasive_ventilation.fields]]
    field = "ccm_b_noninvasive_prtrt"
    ref = "Y/N/NK"
    description = "Non-invasive ventilation?"

[visit.treatment_nsaid]
  description = "NSAID"
  combinedType = "firstNonNull"

  [[visit.treatment_nsaid.fields]]
    field = "overall_nsaid_cmyn"
    ref = "Y/N/NK"
    description = "Non-steroidal anti-inflammatory (NSAID)?"

  [[visit.treatment_nsaid.fields]]
    field = "daily_nsaid_cmoccur"
    ref = "Y/N/NK"
    description = "Non-steroidal anti-inflammatory (NSAID)?"

  [[visit.treatment_nsaid.fields]]
    field = "nsaid_cmoccur"
    ref = "Y/N/NK"
    description = "Non-steroidal anti-inflammatory (NSAID) on first day of admission?"

[visit.treatment_other]
  field = "ccm_a_other_prtrt"
  description = "Other intervention or procedure not already recorded in this form or in the RAPID Module 2 form?"
  if = { ccm_a_oth_prperf = 1 }

[visit.treatment_oxygen_therapy]
  description = "Oxygen therepy"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_oxygen_cmoccur", ref = "Y/N/NK", description = "Oxygen therepy?" },
    { field = "daily_oxygen_cmoccur", ref = "Y/N/NK", description = "Oxygen therepy?" },
    { field = "oxygen_cmoccur", ref = "Y/N/NK", description = "Oxygen therepy on first day of admission?" },
    { field = "ccm_a_fi02_lbyn", ref = "Y/N/NK", description = "Any supplemental oxygen?" },
  ]

[visit.treatment_prone_position]
  description = "Prone Positioning"
  combinedType = "firstNonNull"
  fields = [
    { field = "overall_prone_prtrt", ref = "Y/N/NK", description = "Prone positioning?" },
    { field = "daily_prone_prtrt", ref = "Y/N/NK", description = "Prone positioning?" },
    { field = "prone_prtrt", ref = "Y/N/NK", description = "Prone position on first day of admission?" },
    { field = "ccm_a_pronevent_prtrt", ref = "Y/N/NK", description = "Prone positioning?" },
    { field = "ccm_b_pronevent_prtrt", ref = "Y/N/NK", description = "Prone positioning?" },
  ]

[visit.treatment_inhaled_nitric_oxide]
  field = "ccm_a_nitritc_cmtrt"
  ref = "Y/N/NK"
  description = "Inhaled nitric oxide?"

[visit.treatment_high_flow_nasal_cannula]
  field = "ccm_b_hhfnc_prtrt"
  ref = "Y/N/NK"
  description = "Humidified high flow nasal cannula (HHFNC)?"

[visit.icu_admission_dates]
  description = "ICU admission date"
  combinedType = "list"
  excludeWhen = "none"
  fields = [
    { field = "overall_icu_hostdat", description = "ICU admission date" },
    { field = "ccm_b_icu_hodat", desription = "ICU admission date" },
  ]

[visit.pathogen_test_date]
  field = "coll_date"
  description = "Collection date"

[visit.outcome]
  field = "dsterm"
  description = "Outcome"

  [visit.outcome.values]
    1 = "discharged"
    2 = "hospitalised"
    3 = "transferred"
    4 = "death"
    5 = "discharged"

[visit.date_outcome]
  field = "dsstdtc"
  description = "Outcome date"
