#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "recover eu"
  description = "recover EU consortium"
  defaultDateFormat = "%m/%d/%Y"

  [adtl.tables.subject]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/subject.schema.json"

  [adtl.tables.visit]
    kind = "groupBy"
    groupBy = "visit_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/visit.schema.json"
    optional-fields = [ "outcome", "country_iso3", "date_outcome" ]

  [adtl.tables.observation]
    kind = "oneToMany"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/observation.schema.json"

  [adtl.defs."Y/N".values]
    1 = true
    2 = false

  
    # SUBJECT
    # required fields - subject_id, country_iso3, admission_date, age, sex_at_birth, ethnicity, pathogen

[subject]
  pathogen = "COVID-19"

  [subject.subject_id]
    field = "subject"
    sensitive = true

  [subject.enrolment_date] # is this correct?
    combinedType = "firstNonNull"
    fields = [
      { field = "IC2_DATE", description = "Date of consent signed:" },
      { field = "incldt", description = "inclusiondate" }
    ]
    
  [subject.earliest_admission_date]
    field = "adm_dt" 
    description = "Date of hospital admission:"

  [subject.age]
    field = "DOB"
    description = "Date of birth:"
    apply = { function = "yearsElapsed", params = [ "$adm_dt", 2022, "%m/%d/%Y", "%m/%d/%Y", ] }

  [subject.sex_at_birth]
    field = "sex"
    description = "Gender at birth:"

    [subject.sex_at_birth.values]
      1 = "male"
      2 = "female"

[subject.ethnicity] # Not sure about below and field names
  combinedType = "set"
  excludeWhen = "none"
  fields = [
    { field = "etn_opt1", description = "Ethnicity/background: White/Caucasian", values = { 1 = "White" } },
    { field = "etn_opt2", description = "Ethnicity/background: Black", values = { 1 = "Black" } },
    { field = "etn_opt3", description = "Ethnicity/background: Asian", values = { 1 = "Asian" } },
    { field = "etn_opt4", description = "Ethnicity/background: Other", values = { 1 = "Other" } },
    { field = "etn_opt4_spec", description = "Ethnicity/background: Other, please specify:" }
  ]

[subject.pregnancy]
  field = "pregn"
  ref = "Y/N"

[subject.pregnancy_date_of_delivery]
  field = "P_PART_Y_DEL_DT"
  description = "Post partum Delivery date"

[subject.has_tuberculosis] # checkbox field?
  field = "CPD_TBC"
  description = "A. Chronic Pulmonary Disease: Tuberculosis"
  ref = "Y/N"

[subject.has_dementia] # checkbox field
  field = "CNEURO_DEMENT"
  description = "Chronic Neurologic Disease -  Dementia / Cognitive dysfunction"
  ref = "Y/N"

[subject.has_rheumatologic_disorder] # checkbox field
  field = "COTH_RHEUM"
  description = "Chronic Other Disease -  Rheumatologic/autoimmune disease"
  ref = "Y/N"

[subject.has_hiv]
  field = "CIMMUN_HIV"
  description = "D. Chronic Immunosuppression: HIV"
  ref = "Y/N"

[subject.has_hypertension]
  field = "CARD_HYPER"
  description = "B. Chronic Cardiovasculair Disease : Hypertension"
  ref = "Y/N"

[subject.has_malignant_neoplasm]
  combinedType = "any"
  fields = [
    { field = "CIMMUN_MALIGN_METAS", description = "Chronic Immunosuppression - Any malignancy within 5 years - metastatic?", ref = "Y/N" },
    { field = "CIMMUN_MALIGN", description = "Chronic Immunosuppression - Any malignancy within 5 years", ref = "Y/N" }
  ]
  
[subject.has_smoking]
  field = "smoke"
  description = "Smoking:	"

  [subject.has_smoking.values]
    3 = "yes" # 3="Current smoker (>=1 cigarette per day)"
    2 = "former" # 2="Stopped smoking but used to smoke regularly"
    1 = "never" # 1="Never smiked regulary"

[subject.has_asthma] # checkbox field
  field = "CPD_AST"
  description = "A. Chronic Pulmonary Disease: Asthma"
  ref = "Y/N"

[subject.has_chronic_cardiac_disease]
  field = "chr_card"
  description = "Chronic Cardiovascular Disease"
  ref = "Y/N"

[subject.has_chronic_kidney_disease]
  field = "COTH_RENAL"
  description = "Chronic Other Disease -  Chronic Renal disease"
  ref = "Y/N"

[subject.has_diabetes] # checkbox fields
  combinedType = "any"
  fields = [
    { field = "CMETAB_DB1", description = "C. Chronic Metabolic/Endocrine Disease : Diabetes type 1", ref = "Y/N" },
    { field = "CMETAB_DB2A", description = "C. Chronic Metabolic/Endocrine Disease : Diabetes type 2, medicated (only oral medication)", ref = "Y/N" },
    { field = "CMETAB_DB2B", description = "C. Chronic Metabolic/Endocrine Disease : Diabetes type 2, medicated (insulin dependent)", ref = "Y/N" }
  ]

[subject.has_liver_disease] # checkbox field
  field = "COTH_LIVER"
  description = "F. Chronic Other Disease : Chronic Liver disease"
  ref = "Y/N"

[subject.has_solid_organ_transplant] # checkbox field
  field = "CIMMUN_ORG_TRANS"
  description = "Chronic Immunosuppression - Solid organ transplant"
  ref = "Y/N"

[subject.has_hiv_art]
  field = "CIMMUN_HIV_ANTI_THER"
  description = "Chronic Immunosuppression - HIV - Currently on antiretroviral therapy?"
  ref = "Y/N"

[subject.has_immunosuppression]
  field = "chr_immuno"
  description = "Chronic Immunosuppression (due to disease)"
  ref = "Y/N"

[subject.has_asplenia]
  field = "CIMMUN_ASPL"
  ref = "Y/N"

[subject.has_comorbidity_other] # type - array
  combinedType = "set"
    excludeWhen = "none"
    fields = [
      { field = "COTH_OTHER_SPEC" },
    ]

[subject.date_death]
  field = "ddate"
  description = "Date of death"

[subject.icu_admitted]
  combinedType = "any"
    fields = [
      { field = "COV19_ICU", description = "Was the patient treated in ICU?", ref = "Y/N" },
      { field = "ICUadm_y", description = "Did episode included ICU/High Care Unit admission?", ref = "Y/N" },
    ]

  # VISIT
  # required fields - "visit_id", "subject_id", "country_iso3", "start_date", "outcome", "date_outcome"

[visit]
  [visit.visit_id]
    field = "subject"
    sensitive = true

  [visit.subject_id]
    field = "subject"
    sensitive = true

  [visit.start_date]
    field = "adm_dt"

  [visit.icu_admission]
    combinedType = "any"
    fields = [
      { field = "COV19_ICU", description = "Was the patient treated in ICU?", ref = "Y/N" },
      { field = "ICUadm_y", description = "Did episode included ICU/High Care Unit admission?", ref = "Y/N" },
    ]

  [visit.icu_admission_dates]
    field = "ICUadm_dt"
    description = "Admission date ICU/HCU:"

  [visit.treatment_corticosteroid]
    combinedType = "any"
    fields = [
      { field = "steroids_op1", description = "Steroids - Inhaled corticosteroids", values = { 1 = true, 0 = false } },
      { field = "steroids_op2", description = "Steroids  - Oral low  dose steroids", values = { 1 = true, 0 = false } },
      { field = "steroids_op2", description = "Steroids - Oral high  dose  steroids", values = { 1 = true, 0 = false } },
      { field = "CORT", ref = "Y/N" },
    ]

  [visit.treatment_ace_inhibitors]
    field = "medication_op1"
    values = { 1 = true, 0 = false }
    
  [visit.treatment_invasive_ventilation]
    field = "INTMV"
    description = "Did participant receive any intubation and mechanical ventilation"
    ref = "Y/N"

  [visit.treatment_antivirals]
    field = "AV"
    ref = "Y/N"

  [visit.treatment_antifungal_agent]
    field = "AF"
    ref = "Y/N"

  [visit.treatment_oxygen_therapy]
    combinedType = "any"
    fields = [
      { field = "O2", description = "Did participant receive any supplemental O2?", ref = "Y/N" },
      { field = "NIMV", description = "Did participant receive any non-invasive mechanical ventilation", values = { 2 = true, 3 = false } },
      { field = "INTMV", description = "Did participant receive any intubation and mechanical ventilation" },
      { field = "Prone_pos", description = "Prone position ventilation (any time)" },
    ]

  [visit.treatment_prone_position]
    field = "Prone_pos"
    ref = "Y/N"

  [visit.treatment_antibiotics]
    field = "AB"
    ref = "Y/N"

  [visit.date_outcome]
    field = "disch_dt"
    description = "Discharge date:"

    # OBSERVATION
    # required fields - phase, date, name

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  value = { field = "values_diast" }

[[observation]]
  name = "altered_consciousness_confusion"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  is_present = { field = "ment_conf", ref = "Y/N" }

[[observation]]
  name = "confusion"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  is_present = { field = "ment_conf", ref = "Y/N" }

[[observation]]
  name = "severe_dehydration"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  is_present = { field = "SHOCK", ref = "Y/N" }

[[observation]]
  name = "heart_rate_bpm"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  value = { field = "HRATE" }

[[observation]]
  name = "oxygen_saturation_percent"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  value = { field = "SpO2_perc" }
  context.combinedType = "set"
  context.excludeWhen = "none"
  context.fields = [
    { field = "SpO2_on", values = { 1 = "Room air", 2 = "Supplemental O2 (any)" } }
  ]

[[observation]]
  name = "respiratory_rate"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  value = { field = "RESP_RATE" }
  
[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  value = { field = "values_syst" }

[[observation]]
  name = "temperature_celsius"
  date = { field = "adm_dt" } # not sure about this??
  phase = "admission" # not sure about this??
  value = { field = "tempX" }

