#:schema ../../schemas/dev/parser.schema.json

[adtl]
  name = "StopCOVID Russia"
  description = "CVMEWUS StopCOVID cohort, Sechenov University hospital network, Moscow, Russia, 2020"

  [adtl.tables.subject]
    kind = "groupBy"
    groupBy = "subject_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/subject.schema.json"
    optional-fields = ["ethnicity"]

  [adtl.tables.visit]
    kind = "groupBy"
    groupBy = "visit_id"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/visit.schema.json"

  [adtl.tables.observation]
    kind = "oneToMany"
    aggregation = "lastNotNull"
    schema = "../../schemas/dev/observation.schema.json"

  [adtl.defs."Y/N".values]
    1 = true
    2 = false

  [adtl.defs.boolean.values]
    1 = true
    0 = false

[adtl.defs.admissionDate]
  field = "hostdat"

[adtl.defs.followupDate]
  field = "flw_survey_date"

[adtl.defs.followupDuration.values]
  1 = "1-2 weeks"
  2 = "> 2-4 weeks"
  3 = ">1-2 months"
  4 = ">2-3 months"
  5 = ">3-6 months"
  7 = "Since the hospital discharge"

[adtl.defs.severity.values]
  1 = "caused bearable discomfort/was controlled"
  2 = "caused severe discomfort/was not controlled"
  3 = "the reason for calling an ambulance/visit a doctor"

[subject]
  pathogen = "COVID-19"

  [subject.age]
    field = "flw_date_birth"
    apply = { function = "yearsElapsed", params = ["$hostdat"] }

  [subject.subject_id]
    field = "subjid"
    sensitive = true

  [subject.earliest_admission_date]
    ref = "admissionDate"

  [subject.sex_at_birth]
    field = "flw_sex_at_birth"
    values = { 1 = "male", 2 = "female" }
    # no pregnancy related information in data dictionary

  [subject.has_chronic_hematologic_disease]
    field = "chronhaemo_mhyn"
    ref = "Y/N"

  [subject.has_asplenia]
    field = "asplenia_mhyn"
    ref = "Y/N"

  [subject.has_obesity]
    field = "obesity_mhyn"
    ref = "Y/N"

  [subject.has_tuberculosis]
    field = "tb_mhyn"
    ref = "Y/N"

  [subject.has_dementia]
    field = "dementia_mhyn"
    ref = "Y/N"

  [subject.has_rheumatologic_disorder]
    field = "rheumatology_mhyr"
    ref = "Y/N"

  [subject.has_hiv]
    field = "aidshiv_mhyn"
    ref = "Y/N"

  [subject.has_hypertension]
    field = "hypertension_mhyn"
    ref = "Y/N"

  [subject.has_malignant_neoplasm]
    field = "malignantneo_mhyn"
    ref = "Y/N"

  [subject.has_smoking]
    field = "smoking_mhyn"
    values = { 1 = "yes", 2 = "never", 3 = "former" }

  [subject.has_asthma]
    field = "asthma_mhyn"
    ref = "Y/N"

  [subject.has_chronic_cardiac_disease]
    field = "chroniccard_mhyn"
    ref = "Y/N"

  [subject.has_chronic_kidney_disease]
    field = "renal_mhyn"
    ref = "Y/N"

  [subject.has_diabetes]
    combinedType = "any"
    fields = [ # not mapping false, as it does not imply absence of diabetes
      { field = "diabetes_mhyn", values = { 1 = true } },
      { field = "diabetiscomp_mhyn", values = { 1 = true } },
      { field = "diabetes_mhyn_2", values = { 1 = true, 2 = true } },
    ]

  [subject.diabetes_type]
    field = "diabetes_mhyn_2"
    values = { 1 = "type-1", 2 = "type-2" }

  [subject.has_liver_disease]
    combinedType = "any"
    fields = [
      { field = "modliver_mhyn", ref = "Y/N" },
      { field = "mildliv_mhyn", ref = "Y/N" },
    ]

  [subject.has_hiv_art]
    field = "aidshiv_mhyn_2"
    # 1, YES-on ART | 2, YES-not on ART | 3, No | 4, Unknown
    values = { 1 = true, 2 = false, 3 = false }

  [subject.has_malnutrition]
    field = "malnutrition_mhyn"
    ref = "Y/N"

  [subject.has_died] # type - boolean
    field = "dsterm"                                                  # outcome
    values = { 1 = false, 2 = false, 3 = false, 4 = true, 5 = false }

  [subject.date_death]
    field = "dsstdtc"
    description = "Outcome death"
    if.dsterm = 4

  [subject.icu_admitted]
    field = "icu_hoterm"
    ref = "Y/N"

    # VISIT

[visit]
  country_iso3 = "RUS"

  [visit.visit_id]
    field = "subjid"
    sensitive = true

  [visit.subject_id]
    field = "subjid"
    sensitive = true

  [visit.start_date]
    field = "flw_date_symptoms"

    # There is pathogen test information, but no test date
    # [visit.pathogen_test_date]
    #   field = ""
    #   description = ""

  [visit.icu_admission]
    field = "icu_hoterm"
    ref = "Y/N"

  [visit.icu_admission_dates]
    combinedType = "set"
    excludeWhen = "none"
    fields = [{ field = "icu_hostdat" }]

  [visit.treatment_dialysis]
    field = "rrt_prtrt"
    ref = "Y/N"

  [visit.treatment_inotropes_vasopressors]
    field = "inotrop_cmtrt"
    ref = "Y/N"

  [visit.treatment_ecmo]
    field = "extracorp_prtrt"
    ref = "Y/N"

  [visit.treatment_oxygen_therapy]
    combinedType = "any"
    fields = [
      { field = "oxygen_cmoccur", ref = "Y/N" },
      { field = "noninvasive_proccur", ref = "Y/N" },
      { field = "invasive_proccur", ref = "Y/N" },
      { field = "nasal_highflow_proccur", ref = "Y/N" }, # high flow nasal cannula
      { field = "pronevent_prtrt", ref = "Y/N" },        # prone ventilation
    ]

  [visit.treatment_prone_position]
    field = "pronevent_prtrt"
    ref = "Y/N"

  [visit.treatment_invasive_ventilation]
    field = "invasive_proccur"
    ref = "Y/N"

  [visit.treatment_inhaled_nitric_oxide]
    field = "inhalednit_cmtrt"
    ref = "Y/N"

  [visit.treatment_noninvasive_ventilation]
    field = "noninvasive_proccur"
    ref = "Y/N"

  [visit.treatment_high_flow_nasal_cannula]
    field = "nasal_highflow_proccur"
    ref = "Y/N"

    # [visit.treatment_cardiovascular_support] nothing other than ECMO

  [visit.outcome]
    field = "dsterm"

    [visit.outcome.values]
      1 = "discharged"
      2 = "hospitalised"
      3 = "transferred"
      4 = "death"
      5 = "palliative discharge"

[visit.date_outcome]
  field = "dsstdtc"

  # OBSERVATION

[[observation]]
  name = "diastolic_blood_pressure_mmHg"
  date.ref = "admissionDate"
  phase = "admission"
  value = { field = "admission_diabp_vsorres" }
  if.diabp_vsyn = 1

[[observation]]
  name = "systolic_blood_pressure_mmHg"
  date.ref = "admissionDate"
  phase = "admission"
  value = { field = "sysbp_vsorres" }
  if.sysbp_vsyn = 1

[[observation]]
  name = "abdominal_pain"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "abdopain_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "fatigue_malaise"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "fatigue_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "anorexia"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "anorexia_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "confusion"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "confusion_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "muscle_aches"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "myalgia_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "joint_pain"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "jointpain_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "diarrhoea"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "diarrhoea_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "vomiting_nausea"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "vomit_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "vomiting_nausea"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "vomit_cov", ref = "boolean" }

[[observation]]
  name = "skin_rash"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "rash_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "bleeding_haemorrhage"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "bleed_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "loss_of_smell"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "anosmia_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "loss_of_taste"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "ageusia_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "loss_of_smell_or_taste"
  date.ref = "admissionDate"
  phase = "admission"
  is_present.combinedType = "any"
  is_present.fields = [
    { field = "anosmia_ceoccur_v2", ref = "Y/N" },
    { field = "ageusia_ceoccur_v2", ref = "Y/N" }
  ]

[[observation]]
  name = "seizures"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "seizures_cecoccur_v2", ref = "Y/N" }

[[observation]]
  name = "seizures"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_seizures", ref = "boolean"}

[[observation]]
  name = "headache"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "headache_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "severe_dehydration"
  phase = "admission"  # TODO: not sure, check
  date.ref = "admissionDate"
  is_present = { field = "dehydration_vsorres", ref = "Y/N"}

[[observation]]
  name = "lymphadenopathy"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "lymp_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "conjunctivitis"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "conjunct_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "chest_pain"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "chestpain_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "lower_chest_wall_indrawing"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "lowerchest_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "shortness_of_breath"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "shortbreath_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "shortness_of_breath"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_breathless", ref = "boolean" }

[[observation]]
  name = "wheezing"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "wheeze_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "sore_throat"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "sorethroat_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "runny_nose"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "runnynose_ceoccur_v2", ref = "Y/N" }

[[observation]] # TODO: use combinedType here
  name = "cough"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "cough_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "history_of_fever"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "fever_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "inability_to_walk"
  date.ref = "admissionDate"
  phase = "admission"
  is_present = { field = "inablewalk_ceoccur_v2", ref = "Y/N" }

[[observation]]
  name = "loss_of_smell"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_loss_smell", ref = "boolean" }

[[observation]]
  name = "loss_of_taste"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_loss_taste", ref = "boolean" }

[[observation]]
  name = "loss_of_smell_or_taste"
  date.ref = "followupDate"
  phase = "followup"
  is_present.combinedType = "any"
  is_present.fields = [
    { field = "flw_loss_smell", ref = "boolean" },
    { field = "flw_loss_taste", ref = "boolean" }
  ]

[[observation]]
  name = "chest_pain"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_chest_pains", ref = "boolean" }

[[observation]]
  name = "abdominal_pain"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_stomach_pain", ref = "boolean" }

[[observation]]
  name = "diarrhoea"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_diarrhoea", ref = "boolean" }

[[observation]]
  name = "muscle_aches"
  date.ref = "followupDate"
  phase = "followup"
  # TODO: no flw_mus_pain present, check if phase is correct
  is_present = { field = "mus_pain", ref = "boolean" }

[[observation]]
  name = "confusion"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_confusion", ref = "boolean" }

[[observation]]
  name = "skin_rash"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_skin_rash", ref = "boolean" }

[[observation]]
  name = "bleeding"
  date.ref = "followupDate"
  phase = "followup"
  is_present = { field = "flw_bleeding", ref = "boolean" }

[[observation]]
  name = "temperature_celsius"
  phase = "admission"
  date.ref = "admissionDate"
  value.field = "temp_vsorres"
  value.unit = "celsius"
  value.source_unit = { field = "temp_vsorresu", values = { 1 = "celsius", 2 = "fahrenheit" } }

[[observation]]
  name = "heart_rate_bpm"
  phase = "admission"
  date.ref = "admissionDate"
  value.field = "hr_vsorres"

[[observation]]
  name = "respiratory_rate"
  phase = "admission"
  date.ref = "admissionDate"
  value.field = "rr_vsorres"

[[observation]]
  name = "oxygen_saturation_percent"
  phase = "admission"
  date.ref = "admissionDate"
  value.field = "oxy_vsorres"
  context.combinedType = "set"
  context.excludeWhen = "none"
  context.fields = [
    { field = "oxy_vsorresu", values = { 1 = "Room air", 2 = "Oxygen therapy" } },
  ]

[[observation]]
  name = "sternal_capillary_refill_time_greater_2s"
  phase = "admission"
  date.ref = "admissionDate"
  is_present = { field = "stercap_vsorres", ref = "Y/N" }

[[observation]]
  name = "inability_to_walk_scale"
  phase = "followup"
  date.ref = "followupDate"
  # TODO: there is also flw_eq5d_mb_5l_uk_eng_2
  value.field = "flw_eq5d_mb_5l_uk_eng"

  [observation.value.values]
    1 = 1 # You have no problems in walking about?
    2 = 2 # You have slight problems in walking about?
    3 = 2 # You have moderate problems in walking about?
    4 = 3 # You have severe problems in walking about?
    5 = 4 # You are unable to walk about?

[[observation]]
  name = "oxygen_flow_volume_max"
  phase = "study"
  date.ref = "admissionDate"  # TODO: could not find study date
  text.field = "oxygen_cmdose"

  [observation.text.values]
    1 = "< 2 L/min"
    6 = "2-5 L/min"
    2 = "6-10 L/min"
    3 = "11-15 L/min"
    4 = ">15 L/min"
