name: schemas

on:
  push:
    branches: [ main ]
    paths:
    - 'scripts/test-schemas/*.py'
    - 'schemas/dev/*.json'
    - '.github/workflows/schemas.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'scripts/test-schemas/*.py'
    - 'schemas/dev/*.json'
    - '.github/workflows/schemas.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Lint with flake8
      run: |
        python3 -m pip install flake8 pytest
        # stop the build if there are Python syntax errors or undefined names
        flake8 scripts/test-schemas --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 scripts/test-schemas --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install dependencies
      run: |
        python3 -m pip install -r scripts/test-schemas/requirements.txt
    - name: Test with pytest
      run: |
        python3 -m pytest scripts/test-schemas/
